### ISSUE TITLE
Feature-Request: Farbgestaltung

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#1]
Hallo,

bitte eine Farbgestaltung für Icons, Hintergrundbild, Wert einbauen.
Danke
LG
Sigi

**Comment by peter9teufel** [comment]
Versteh ichs richtig, du möchtest pro Datenpunkt festlegen können:

- Farbe des Icons
- Farbe des Textes
- Hintergrund der Karte (Farbe oder Bild)

Oder meinst du mit Hintergrund generell ein Hintergrundbild für eine Seite festlegen zu können?

LG

**Comment by sigi2345** [comment]
> Versteh ichs richtig, du möchtest pro Datenpunkt festlegen können:
> 
> * Farbe des Icons
> * Farbe des Textes
> * Hintergrund der Karte (Farbe oder Bild)
> 
> Oder meinst du mit Hintergrund generell ein Hintergrundbild für eine Seite festlegen zu können?
> 
> LG

Beides

**Comment by peter9teufel** [comment]
Bau ich nach den Bugs ein 👍
