### ISSUE TITLE
Feature-Request: Slider 

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#10]
Hallo,

kann man beim Typ Slider noch folgendes integrieren:

![Screenshot (808)](https://github.com/peter9teufel/iobmobile-issues/assets/41079106/aca04a85-2a0c-4a30-af14-b1bb9b2c383f)

Zumindest min/max/step

**Comment by peter9teufel** [comment]
Hi,
sollte kein Problem sein 👍

**Comment by peter9teufel** [comment]
Version 1.0.4 ist bereits eingereicht, wenn Typ "Slider" ausgewählt ist gibt es jetzt die Option "Werte anzeigen", wenn das ausgewählt ist wird die Sliderbeschriftung angezeigt, da dafür mehr Platz nötig ist und die Karte mind. 2 Zeilen hoch sein muss wird in diesem Modus auch der aktuelle Wert angezeigt.

Ich hab jetzt nicht alle Einstellungen die du markiert hast im Detail umgesetzt im ersten Anlauf, die App entscheidet je nach Kartengröße selbst wie viele Beschriftungen und Ticks dazwischen angezeigt werden. Durch Tap auf einen Tick/Wert in der Beschriftung kann dieser auch gesetzt werden.

Probier das mal so aus ob das für dich so verwendbar ist, ich kanns natürlich auch noch um alle Detaileinstellungen erweitern, dauert aber noch ein paar Tage weil ich das so einbauen würde, dass der User explizit sagen muss dass er diese Einstellungen selbst im Detail definieren will.

Update für Android im Laufe des Vormittages, für iOS dann vermutlich auch heute im Laufe des Tages (je nachdem wie schnell Apple ist).

LG

**Comment by sigi2345** [comment]
Super , der Wert min/max wäre noch gut.
Ich habe einen Yamaha Verstärker wo die Lautstärke in Db ist.  Der geht von -80 bis 0

**Comment by sigi2345** [comment]
Bei Min/Max sind keine Minus Werte möglich.

Version 1.0.5

**Comment by peter9teufel** [comment]
Oh dummer Fehler, Update folgt.

LG

**Comment by peter9teufel** [comment]
1.0.6 ist im Google Play Store, Tastaturtyp ist angepasst, jetzt können für Min/Max auch negative Werte und Dezimalzahlen eingegeben werden.

LG

**Comment by sigi2345** [comment]
> 1.0.6 ist im Google Play Store, Tastaturtyp ist angepasst, jetzt können für Min/Max auch negative Werte und Dezimalzahlen eingegeben werden.
> 
> LG

Leider noch nicht.

**Comment by peter9teufel** [comment]
Gerade nochmal nachgesehen, die Version ist verfügbar und hat auch das geänderte Layout, hier zB auf einem Huawei Testgerät.

![image](https://github.com/peter9teufel/iobmobile-issues/assets/1713402/cbd5975b-a0c4-42ea-8540-cc64357a1d8b)

**Comment by sigi2345** [comment]
> Gerade nochmal nachgesehen, die Version ist verfügbar und hat auch das geänderte Layout, hier zB auf einem Huawei Testgerät.
> 

Ok, habe ein Samsung da gibt es ein eigenes Tastaturlayout. Habe es mal umgestellt.
Die Werte werden aber nicht übernommen.

![Screenshot_20240615_082340](https://github.com/peter9teufel/iobmobile-issues/assets/41079106/a75a31ce-8f1f-4e59-83fb-8d1fc150da5c)


LG
Sigi

**Comment by sigi2345** [comment]
Ja, Yamaha ist da eigen. Belassen wir es mal so.
Wenn du Musiccast funktioniert gibt einen anderen DP für Volume  (0-161)

**Comment by peter9teufel** [comment]
Kannst du mal Default Min/Max Werte wiederherstellen versuchen? Evt. erlaubt der DP in ioBroker keine negativen Werte

**Comment by sigi2345** [comment]
> Kannst du mal Default Min/Max Werte wiederherstellen versuchen? Evt. erlaubt der DP in ioBroker keine negativen Werte

Ja, habe den DP umgestellt. Jetzt geht es :

![Screenshot (841)](https://github.com/peter9teufel/iobmobile-issues/assets/41079106/f26603c5-18a5-4dc8-83ce-441da1e793d4)
