### ISSUE TITLE
Bug: Icon Url wird nicht angezeigt

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#11]
Hallo,

der DP als Typ HTML wird nicht angezeigt:

https://www.wunderground.com/static/i/c/v4/11.svg

Es hatte schon mal funktioniert, wenn ich mich nicht Irre. 

LG
Sigi

**Comment by peter9teufel** [comment]
Für Icons/Bilder kommt ein eigener DP Typ im nächsten Update der das richtig anzeigt, damit sollte das dann korrekt funktionieren

Lg
