### ISSUE TITLE
Bestätigungslink funktioniert nicht 

### ISSUE THREAD

**Issue by ali86x** [peter9teufel/iobmobile-issues#12]
Habe die App gerade auf Android installiert.
Account angelegt und Bestätigungsmail angefordert.
Klicke ich auf den Link erscheint nur das.
In der App komme ich auch nicht weiter. 
![Screenshot_20240629-220917](https://github.com/peter9teufel/iobmobile-issues/assets/97473477/5a46fe3a-4f5e-4fdb-957c-ddc63dff1fa2)
![Screenshot_20240629-220927](https://github.com/peter9teufel/iobmobile-issues/assets/97473477/1fcff78a-9af2-478c-8434-49c977c2bc62)

**Comment by peter9teufel** [comment]
Seltsam, der Link öffnet im Normalfall direkt die App um den Account zu aktivieren. Ich seh mir das an, vielen Dank für den Hinweis!

LG,
Peter

**Comment by ali86x** [comment]
Hab's hinbekommen. Kann eine falsche Einstellung bei mir am Handy sein. 
Ich musste in den App Einstellungen explizit der IOB App den Link zuweisen. 
Jetzt geht's. 
![Screenshot_20240630-083033](https://github.com/peter9teufel/iobmobile-issues/assets/97473477/c99be993-c1c2-43f5-afd4-4f9f9fc84184)
![Screenshot_20240630-083048](https://github.com/peter9teufel/iobmobile-issues/assets/97473477/0c7da29c-481c-4bbb-99fc-5eeb44162ca6)

**Comment by peter9teufel** [comment]
ah perfekt, danke für die Rückmeldung. Hab heute früh trotzdem noch eingebaut, dass der Bestätigungslink auch manuell in der App eingefügt werden kann, dann kann so etwas in Zukunft auch auf anderem Wege gelöst werden.

Danke für die Info, dann mach ich hier mal zu 👍
