### ISSUE TITLE
eigene Datenpunkte für Schaltaktionen

### ISSUE THREAD

**Issue by robert-ke** [peter9teufel/iobmobile-issues#13]
Hallo an das Entwicklerteam.

Vielen Dank zuerstmal für diesen tollen Projektstart und das Vorhaben - ich bin dabei :-)

Frage: Wäre es denkbar, dass man bei einem Datenpunkt, der z. B. ein Schalter für True/False ist, auch einen anderen Datenpunkt zum wegschreiben einstellen kann?

Usecase wäre z. B. bei mir:
Ich kriege per Script von meiner eigenen Haussteuerung (Hardwareseite SPS) alle Werte fürs ganze Objekt in einer Datenstruktur. Die Werte sind alle aber nur zum Lesen - das heißt, eine Lampe kann ich hier sehen, ob true oder false.

Jedoch passiert nichts, wenn ich diesen Wert im Objekt verändere. Ich müsste einen beliebigen Text in ein frei definierbares Objekt schreiben können, z. B. in 0_userdata.SPS.SendValue - wenn ich in dieses Objekt reinschreibe, KuecheLichtEin dann verarbeitet im Hintergrund ein Script die Ansteuerung zur SPS - das heißt, ich bräuchte einen Freitext für Wert True und einen Freitext für Wert False.

Wenn diese Möglichkeit gegeben ist, könnte ich das komplett verwenden und auch für ein paar meiner Haussteuerungskunden verwenden und an den Mann bringen.

Danke & Gruß,
Robert

**Comment by peter9teufel** [comment]
Hallo Robert,
denke das lässt sich umsetzen, muss ich mir im Detail überlegen, aber durchaus ein UseCase - werd ich einbauen.

ich geb dir hier im Ticket Updates dazu 👍

Lg,
Peter

**Comment by robert-ke** [comment]
Hallo Peter,

das wäre natürlich super. Und wenn man bei der Gelegenheit auch die Möglichkeit bekommt, den 0_userdata auszulesen wäre damit vielleicht auch vielen geholfen, anstelle nur Objekte von Adaptern anzeigen zu können. Ich denke, jeder hat eigene Scripte/Blocklys am laufen und schreibt irgendwelche Werte in eigenen Objekte. Dann könnte man diese auch anzeigen/verwenden.

Danke & Gruß,
Robert

**Comment by peter9teufel** [comment]
Hi,
Objekte aus 0_userdata werden schon seit Beginn unterstützt 👍 ohne die würd ich selbst nämlich auch nicht auskommen 😄 

LG,
Peter

**Comment by robert-ke** [comment]
Okay, das seh ich auf anhieb noch nicht wie ich an die 0_userdata Objekte komme.

**Comment by robert-ke** [comment]
oh mei :-) Alles klar, war zu einfach - Danke, passt. Dann wart ich mal noch auf Feedback bzgl. der frei definierbaren Aktionen in Objekte - Danke einstweilen

**Comment by peter9teufel** [comment]
Hi!
Hab gerade das Update für Version 1.0.15 eingereicht, sobald es von Apple und Google gerpfüt und freigegeben ist sollte es im Laufe des Tages in den App Stores verfügbar sein.

Beim Typ "Eigenen Wert schreiben", bei dem ja ein eigener Wert festgelegt werden kann der geschrieben werden soll, gibt es ab Version 1.0.15 die zusätzliche Option "In anderen Datenpunkt schreiben", diese erlaubt es, den Wert in einen anderen Datenpunkt zu schreiben. Somit wird der Wert des Datenpunktes den man konfiguriert in der Kachel angezeigt, wenn man draufklickt wird der konfigurierte eigene Wert in den anderen Datenpunkt geschrieben den man in der Konfiguration festgelegt hat.

Damit sollte sich dein Use Case jetzt abbilden lassen.

Im Google Play Store sollte das Update in den nächsten Stunden verfügbar sein (im Normalfall 2-3 Stunden), bei Apple dauert es gerne etwas länger bis die Überprüfung durch ist, aber ich gehe mal davon aus dass das Update auch da bis zum Abend, spätestens morgen früh online sein müsste.

LG,
Peter

**Comment by peter9teufel** [comment]
hab grad erst oben gesehen, dass du auch gern 2 Werte hättest, das hatte ich bisher überlesen. Dazu gibts schon ein anderes Issue (siehe Issue #24), wird im nächsten Update kommen, dass man mehrere Werte hinterlegen kann von denen man dann einen beim Tippen auf die Kachel auswählen kann der gesendet werden soll.

Sorry hatte das komplett überlesen mit den 2 Werten 😃 

LG

**Comment by robert-ke** [comment]
Hallo Peter,

Sorry für die späte Rückmeldung - aber das schaut schon mal alles recht gut aus, wie es umgesetzt ist 👍😎 Ja, bei den 2 Werten ging es mir um folgenden Ablauf:

Klickt man auf den Button, wenn er AN ist - soll ein Wert für AUS definiert werden können. Wenn der Button AUS ist, ein Wert für den EIN Befehl. Hintergrund ist quasi relativ einfach:

-> Ich habe Befehle, wie z. B. Lampen etc., die per UMSCHALTEN Befehl weggearbeitet werden. Dort ist es einfach, jeder klick auf den Button egal welcher Zustand er hat, immer den gleichen Wert ins Objekt schalten.
-> Dann gibt es aber Befehle, die explizit einen Befehl für "ausschalten" und "einschalten" haben.

Ich schau mir den Issue mal an, was da eh schon kommt, evtl. kann ichs damit gleich erschlagen. Aber generell kann ich schon mal loslegen damit - Danke einstweilen

**Comment by peter9teufel** [comment]
Hi,
ich werd heute noch ein Update einreichen, dieses erlaubt beim Typ "Eigenen Wert schreiben" dann, dass man mehrere mögliche Werte die geschrieben werden können per Komma getrennt eingeben kann, zusätzlich gibt man die Anzeigenamen der Werte (ebenfalls kommasepariert) an. Wenn man dann auf die Kachel klickt, kommt ein Popup in dem man wählt, welcher Wert gesendet werden soll. 

Das wär also mal die flexible Variante die theoreitsch auch 5 verschiedene vordefinierte Werte für eine Kachel ermöglichen würde. Ich kann auch noch eine Erweiterung für den Typ "On/Off Button" erstellen, die frei definierbare Werte und einen separaten Datenpunkt zum schreiben erlaubt, das muss ich mir aber genauer anschauen, da der On/Off Button natürlich eines jener Widgets ist die jeder User braucht und das viel genutzt wird, das ist so der Klassiker mit dem vermutlich die meisten starten, da möchte ich sichergehen, dass dieser in der Anwendung simpel ist und nicht durch viele Spezialeinstellungen verkompliziert wird. :smile:

Ich geb dir hier kurz Bescheid wenn das neue Update verfügbar ist.

LG,
Peter

**Comment by peter9teufel** [comment]
Hallo,
Version 1.0.17 ist jetzt verfügbar.

LG,
Peter

**Comment by peter9teufel** [comment]
da der UseCase grundsätzlich wie oben erklärt jetzt schon abbildbar ist mach ich das Issue mal zu. Wenn noch wo ein Problem auftritt gerne wieder eins aufmachen.

Liebe Grüße,
Peter
