### ISSUE TITLE
Authentifizierung scheitert

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#15]
Moin,

die Klartext-Authentifizierung, also ohne HTTPS, klappt nicht.
Bei Socket.IO scheint es zu funktionieren, bei simple.API nicht.

Er wirft einen Logeintrag:

simple-api.0 2024-07-02 18:29:22.376	warn	Invalid password or user name: admin

Das Passwort ist aber korrekt. Vielleicht ein Problem mit Sonderzeichen?

**Comment by peter9teufel** [comment]
Muss ich mir ansehen, normalerweise sollten Sonderzeichen kein Problem sein, auswendig würde mir da nur „#“, „?“ und „&“ einfallen weil diese Zeichen durchaus auch eine Funktion in einer URL haben, ist eins von denen dabei? Bzw. wenn nicht welche Sonderzeichen sind denn dabei?

Lg, Peter

**Comment by HackyPaddy** [comment]
Genau, dass Passwort hat am Ende ein #

**Comment by peter9teufel** [comment]
Kannst du es bitte mal ohne dem # im Passwort versuchen, nur damit wir sehen obs daran liegt?

**Comment by HackyPaddy** [comment]
Gerade getestet, ja das liegt in der Tat an dem #.
Ohne diesem wird das Passwort angenommen.

**Comment by peter9teufel** [comment]
Fehler schon gefunden ist im nächsten Update dann gefixt 👍

**Comment by HackyPaddy** [comment]
Ich bin gespannt.

Und nebenbei ein großes Lob. Die App ist klasse!

**Comment by peter9teufel** [comment]
Update ist eingereicht und sollte im Laufe des Tages in den Stores sein (Apple braucht mit der Prüfung meist etwas länger als Google).

LG
