### ISSUE TITLE
Wunsch Timer Datenpunk

### ISSUE THREAD

**Issue by AntiHeld889** [peter9teufel/iobmobile-issues#16]
Erst wollte ich einmal sagen das ich die App wirklich großartig Finde nach etwas Einfummeln gefällt sie mir sehr gut!

Was ich mir noch wünschen würde ware eine Funktion wo in in einen Datenpunkt eine Zeit schreiben könnte. Ich habe viele Timer als Datenpunkte und würde diese Gerne vom Smartphone aus stellen können.

Viele Grüße

**Comment by peter9teufel** [comment]
Danke fürs Feedback 🙂 
Es gibt aktuell den Typ "Eigenen Wert schreiben" den man für einen Datenpunkt auswählen kann, da ists aktuell so, dass man in den Einstellungen des Datenpunktes schon festlegt welcher Wert geschrieben werden soll. Den könnte ich so anpassen, dass der fix vorgegebene eigene Wert optional ist und wenn dieser nicht gesetzt ist wird man beim Klick auf die Kachel gefragt welcher Wert geschrieben werden soll.

Schau ich mir an 👍

**Comment by AntiHeld889** [comment]
Ja die Typ "Eigenen Wert schreiben" war mir auch aufgefallen, da ist es aber umständlich da man jedes mal in die Konfiguration rein muss.

Das klingt super vielen Dank :)

**Comment by peter9teufel** [comment]
habs grad eingebaut, kommt mit dem nächsten Update noch diese Woche.

LG,
Peter

**Comment by peter9teufel** [comment]
Update (Version 1.0.14) ist eingereicht und wartet auf die Freigabe durch Google und Apple, beim Typ "Eigenen Wert schreiben" kann man den Wert in den Datenpunkt-Einstellungen jetzt auch leer lassen. Wenn dieser leer ist, wird beim Klick auf die Kachel per Dialog eingegeben welcher Wert gesendet werden soll.

Das Update sollte im Laufe des Nachmittages im Google Play Store sein, bei Apple dauert die Prüfung meist etwas länger, aber spätestens morgen sollte es auch im App Store sein.

LG,
Peter

**Comment by AntiHeld889** [comment]
Gerade das Update für IOS gemacht und gleich getestet. Funktioniert wunderbar vielen Dank!

Ich habe auch schon 1-2 weitere Ideen bzw. Vorschläge dafür wurde ich die Tage dann noch ein Issue aufmachen :)

**Comment by peter9teufel** [comment]
Sehr gut, mach das gerne 👍
