### ISSUE TITLE
Kein Kontakt mit ioBroker (simple-api ist rot) 

### ISSUE THREAD

**Issue by ChristianPB** [peter9teufel/iobmobile-issues#17]
Freue mich die App benutzen zu können. Hab schon ein Pro Account registriert.
Hab deine Anleitung gefolgt, komme leider aber nicht zu meinen Daten im ioBroker, wahrscheinlich weil alle Punkte der simple-api rot sind.
Socketio ist grün.
Wie komme ich weiter? Im app kommt nur ein Kreis.
Gruß von Christian

**Comment by peter9teufel** [comment]
Schau mal bei deinen Instanzen beim Web Adapter, der hat eine integrierte simple-api, die muss deaktiviert sein, der simple-api Adapter installiert sein und aktiviert, so hab ichs und der wird sofort grün.

LG,
Peter

**Comment by peter9teufel** [comment]
Habs grad nochmal getestet, die eingebaute Simple-API vom Web Adapter funktioniert bei mir genau so, nur dass dann für SimpleAPI der Port vom Web Adapter (8082) verwendet werden muss.

LG,
Peter

**Comment by ChristianPB** [comment]
Hat leider nicht geklappt. Im Web.0 war das nicht aktiviert.

Die simple-api heißt Simple RESTful API? Stimmt? 

Egal was ich in der ankreuzen, bleibt die rot.

**Comment by peter9teufel** [comment]
Schick mal einen Screenshot von den Einstellungen von der simple-api (Einfache RESTful API) Adapter Instanz.

**Comment by ChristianPB** [comment]
![IMG_20240704_165600.jpg](https://github.com/peter9teufel/iobmobile-issues/assets/46577459/f2e076d4-a545-429a-ba11-385ae6a2e33b)

**Comment by ChristianPB** [comment]
Spielt keine Rolle was da steht. Immer nur rot.
 ![IMG_20240704_165900.jpg](https://github.com/peter9teufel/iobmobile-issues/assets/46577459/1dad2ac8-a7f0-40bb-ae2b-62f021e0c769)

**Comment by peter9teufel** [comment]
Ich habs so (Standardeinstellungen), probier das mal.

![Bildschirmfoto 2024-07-04 um 17 00 23](https://github.com/peter9teufel/iobmobile-issues/assets/1713402/59a31714-005b-49bb-af1a-b8a8b67e9c97)

**Comment by ChristianPB** [comment]
Der simple-api geht jetzt in grün. Die App reagiert aber nicht anders. Habe die ports wieder auf 8087 zurückgesetzt

**Comment by peter9teufel** [comment]
web.0 Instanz Einstellungen:
- [IPv4] 0.0.0.0 - Zugriff von allen IPs zulassen
- Port 8082
- Ausführen als: admin
- keine weiteren Haken gesetzt

simple-api.0 Instanz Einstellungen:
- Als Web-Adapter Erweiterung nutzen: "kein"
- [IPv4] 0.0.0.0 - Zugriff von allen IPs zulassen
- Port 8087
- Ausführen als Benutzer: admin
- keine weiteren Haken gesetzt

In der App:
- IP Adresse des ioBrokers
- SimpleAPI Port 8087
- HTTPs verwenden: nein
- Authentifizierung verwenden: nein

So hab ichs konfiguriert und funktioniert problemlos. Schon mal die App komplett abgewürgt und neu gestartet? Wenns dann auch nicht läuft und bei der Ladeanimation hängen bleibt kannst mal die SocketIO Instanz stoppen und die App komplett neu starten, wenn die Verbindung da auch nicht klappt sollte es zurück gehen auf den Startbildschirm zu den Konfigurationen. Dort kannst du auf deine Konfiguration lange drauftippen und auf Bearbeiten klicken um die Einstellungen noch mal zu prüfen und mit jenen der Instanzen im ioBroker zu vergleichen.

LG

**Comment by ChristianPB** [comment]
Leider nicht. Alle Einstellungen stimmen. Hab auch MQTT deaktiviert um zu testen. Ob wohl die Socketio auf pause steht, bleibt die App beim loading hängen. Habe auch de App de und neuinstalliert ohne Erfolg.
Wie sind deine MQTT Einstellungen?
Christian

**Comment by peter9teufel** [comment]
Wird im ioBroker im Log (Menü "Protokolle") was ausgegeben das weiterhilft? Die MQTT Verbindung würde nicht blockieren, die schlägt im Hintergrund fehl wenn falsch konfiguriert.

Gib mal am Rechner im Browser ein: http://192.168.0.200:8087/objects?type=adapter&prettyPrint
--> natürlich IP Adresse mit jener deines ioBrokers austauschen, da müsste dann jede Menge Textzeugs kommen, im Wesentlichen ein riesiges JSON mit Daten zu allen Adaptern. Wenn das nicht klappt hats nach wie vor was bei der Simple API.

Wenn der Ladekreis angezeigt wird, wird da auch ein IOB Mobile Logo angezeigt? kannst du in dem Stand der App links oben das Menü öffnen?

LG,
Peter

**Comment by ChristianPB** [comment]
Hallo Peter,
Im Log steht nichts von den Adaptern. Auf meinem PC kommt beim eintippen (IP redigiert) eine Mänge Text raus. Beim Handy nur ein ERR_SSL_PROTOCOL_ERROR

Wenn der Ladekreis da ist, sind nur die drei Kreise oben rechts sichtbar und auch aktive beim klicken. Kein Menü links oben

ioBroker Visu -app hat kontakt

**Comment by peter9teufel** [comment]
Hast du in der App beim Konfigurieren https aktiviert?

**Comment by ChristianPB** [comment]
Nein, kein https. 
Deine Backupfunktionen (Prüfen, sichern, wiederherstellen) scheinen zu funktionieren

**Comment by ChristianPB** [comment]
...und mit IP beim Eintrag des namens ist meine Lokale IP:8081 gemeint.?

**Comment by peter9teufel** [comment]
IP ist nur die IP ohne Port 8081, kommunizieren tut die App dann ja über die anderen Posts mit API und SocketIO

**Comment by ChristianPB** [comment]
Wow! Das war der Fehler. Hatte am Anfang die IP ohne Port eingegeben. weil es aber wegen den Anderen Dingen nicht funktionierte habe ich sie doch eingetragen.
Vielen Dank für deine Hilfe.
Christian

**Comment by peter9teufel** [comment]
Kein Problem, freut mich dass es jetzt klappt 👍

Lg, Peter
