### ISSUE TITLE
Überschriften / Seitenunterteilung

### ISSUE THREAD

**Issue by AntiHeld889** [peter9teufel/iobmobile-issues#19]
Es wäre eventuell schön die Seiten mit "Überschriften" unterteilen zu können.

Hier ein Bild als Beispiel:

![neu 2](https://github.com/peter9teufel/iobmobile-issues/assets/4448275/f385689c-76d8-4d1e-b4e0-9b63bf097fd5)

**Comment by peter9teufel** [comment]
Keine schlechte Idee, muss ich mir im Detail überlegen wie ich das umsetzen kann, könnte etwas dauern. Aber ich habs mal in meine Liste der Wünsche gegeben 👍 
LG

**Comment by HackyPaddy** [comment]
Ja, dass wäre echt klasse. So könnte man die Elemente etwas kategorisieren. Macht die ganze Sache deutlich übersichtlicher.

Entweder ne Überschrift linksbündig oder zentriert. 

Top Idee!

**Comment by peter9teufel** [comment]
Jop, die Idee gefällt mir selber auch sehr gut, bin nur noch am rätseln wie ichs umsetzen kann, weil die Positionierung nicht ganz trivial ist (Unterschiedliche Spalten je nach Bildschirmgröße, etc.) 😄 

Meine erste Idee dazu wäre, das über die Unterseiten zu lösen. Wenn man also eine Seite als Unterseite einer anderen anlegt (so wie es ja jetzt schon geht) eine zusätzliche Option um auszuwählen ob diese als Tab oder als Abschnitt auf der Hauptseite liegen soll. Wenn als Tab bleibt alles so wie es jetzt auch ist, wenn als Abschnitt dann wird der Name der Seite die Überschrift (die du gern hättest) und darunter kommen die Kacheln der Unterseite. So wäre auch eindeutig, welche Kacheln in welchem Bereich sein müssen.

LG,
Peter

**Comment by HackyPaddy** [comment]
Das letzte Update ist schon klasse. Aber ich persönlich finde "normale Überschriften" deutlich besser, ohne Verlinkungen auf einer anderen Seite.

Wenn ich z.B. eine Seite mit 6 Kacheln 1x1 habe, dann wäre es klasse, wenn ich oberhalb der Kacheln noch eine Überschrift setzen kann, z.B. im Raster 0,5x4 - also was über die gesamte Breite geht.

So kann man nämlich die Seiten übersichtlicher gestalten.

**Comment by peter9teufel** [comment]
Die Unterteilungen sind auf diesem Weg wie jetzt über Unterseiten einfacher zu nutzen, weil so eindeutig klar ist, welche Datenpunkte in welchem Bereich angezeigt werden, unabhängig davon, ob auf dem Smartphone mit 2 Spalten oder auf einem Tablet je nach Größe mit 4 oder 5 Spalten Breite.

Ich schau mir das mit der Seitenüberschrift an, meinst du damit einfach den Namen der Seite als Überschrift anzuzeigen, so wie auch bei den Bereichen die man als Unterseiten definieren kann, oder gibt es einen Grund, warum die Überschrift einer Seite nicht identisch mit deren Namen sein sollte?

LG,
Peter

**Comment by HackyPaddy** [comment]
Ich mach Dir mal ein Bild fertig. Kann allerdings ein paar Tage dauern, da ich gerade unterwegs bin.

Viele Grüße

**Comment by HackyPaddy** [comment]
Ich bin noch nicht zu dem Bild gekommen, Asche auf mein Haupt ... 😆 

Aber dazu noch ne andere Idee, wie es evtl. leichter umzusetzen wäre.
Aktuell kann man nur auf der Hauptseite einbinden (Als Bereich auf der Hauptseite einbinden). Es wäre besser, wenn dies auch auf den Unterseiten ginge.

Dann könnte man eine Unterseite auf einer Unterseite einbinden, wenn Du verstehst was ich meine. Die eingebundene Unterseite müsste man das aber aus dem Navi löschen, damit es nicht doppelt auftaucht.

Somit wäre das Thema der Überschriften gelungen umgesetzt...

**Comment by philg1234** [comment]
Ich kann mich hier @HackyPaddy anschließen und finde die Idee Klasse.
Es ähnelt sehr meinem Vorschlag, weswegen ich es hier noch mit reinpacke.
_Falls ich einen eigenen Post eröffnen soll, sag einfach Bescheid._

Es wäre auch Klasse, wenn man die Möglichkeit hätte einfache Trennlinien in allen Seiten einzufügen um etwas mehr den Überblick zu behalten.

Wie @HackyPaddy bereits erwähnt hat kann man auch dies mit dem Workaround "unterseiten" und "als Bereich auf Hauptseite anzeigen" bauen, allerdings eben nur auf der Hauptseite.

Ich habe hier ein Beispiel angehängt, wie ich es z.B. auf der Alarm Seite mit diesem Workaround getrennt habe.
Leider geht dies eben nicht, wenn ich z.B. jetzt oben im Reiter auf "Alarm Test" springe.

![image](https://github.com/user-attachments/assets/dac9d1a4-1e95-49aa-85d7-bf68f403aeb1)


Dies wäre noch eine Klasse Erweiterung in meinen Augen 😊.

Danke.

Viele Grüße
Phil

**Comment by peter9teufel** [comment]
Ich hab mir das Thema mal notiert und überleg mir was für simple Trennlinien auf Seiten, muss ich mir mal durchdenken wie ich das einbaue, wäre aber verständlicher als jetzt noch Unterseiten als Bereich von Unterseiten zu ergänzen, denke das wird dann irgendwann unübersichtlich und umständlich in der Verwendung 🙂 

LG,
PEter

**Comment by philg1234** [comment]
Absolut.

Du kannst ja mal in dich gehen, ob du eine Lösung findest.
Ich habe das ganze nur Quick & Dirty umgesetzt, damit ich etwas die Trennung und die Übersichtlichkeit habe.

**Comment by peter9teufel** [comment]
Update (Version 1.0.34) ist eingereicht und sollte spätestens morgen in den Stores erscheinen. Beim Sortier-Icon im Dashboard können jetzt zusätzlich zur Sortierung auf der Seite noch Trennlinien mit Überschrift (wenn die Überschrift leer ist wird nur eine Trennlinie angezeigt) und Kacheln zur Navigation erstellt werden. Somit kann eine Gliederung jetzt gemacht werden und zusätzlich kannst du jetzt Kacheln rein zum Navigieren mit beliebigem Icon erstellen ohne dafür einen speziellen Datenpunkt zu benötigen. Die Bereichstrennungen und Navigationskacheln erscheinen dann in Liste für die Sortierung, anhand des Icons rechts erkennt man ob ein Element ein Datenpunkt, eine Bereichstrennung oder eine Navigationskachel ist. Die Elemente können dann in der Sortierung nach Wunsch einsortiert werden.

Teste mal wenns verfügbar ist und gib Bescheid.

LG,
Peter

**Comment by HackyPaddy** [comment]
Mach ich gerne :)
Ich geb Dir morgen Abend ein Update...

Lg
Patrick

**Comment by sigi2345** [comment]
Hallo,
kann man diese auch farbig gestalten?

**Comment by HackyPaddy** [comment]
Peter,

du bist die Wucht.
Das sieht klasse aus und funktional eine 1+!

So lassen sich Bereiche echt gut unterteilen und alles sieht viel aufgeräumter aus.

Aber mal eine Frage am Rande:

Wenn man einer Seite ein Icon zugewiesen hat, wie kann man das wieder löschen? 😁

Lg
Patrick

**Comment by peter9teufel** [comment]
Farbige Gestaltung kann noch ergänzt werden, Icon löschen schau ich mir an 👍

**Comment by peter9teufel** [comment]
Icon löschen geht mittlerweile auch, bzgl. Farben denk ich mal in Ruhe nach, grundsätzlich wird die Vordergrundfarbe verwendet die für die Seite definiert ist.

LG,
Peter
