### ISSUE TITLE
Bug: Adapteranzeige doppelt

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#2]
Hallo,

die Adapteranzeige ist bei mir doppelt.

![Screenshot_20240605_101705](https://github.com/peter9teufel/iobmobile-issues/assets/41079106/49f1b7c3-43dd-4ed5-a6d0-bbe1b2f50e2e)

LG
Sigi

**Comment by peter9teufel** [comment]
Seltsam, kann ich bei mir gerade nicht reproduzieren diesen Fehler. Passiert das nur bei bestimmten Adaptern?

**Comment by sigi2345** [comment]
> Seltsam, kann ich bei mir gerade nicht reproduzieren diesen Fehler. Passiert das nur bei bestimmten Adaptern?

Bei fast allen, bis auf einige Ausnahmen.

**Comment by peter9teufel** [comment]
kannst du mal im Browser http://<ip-adresse>:<simple-api-port>/objects?type=adapter&prettyPrint aufrufen und mir die Ausgabe hier schicken? also zb. http://192.168.1.100:8087/objects?type=adapter&prettyPrint

bzw. falls du https verwendest dann natürlich vorne "https", wenn du Authentifizierung für den SimpleAPI Adapter verwendest dann am Ende "&user=username&pass=password dranhängen

**Comment by sigi2345** [comment]
> kannst du mal im Browser http://:/objects?type=adapter&prettyPrint aufrufen und mir die Ausgabe hier schicken? also zb. http://192.168.1.100:8087/objects?type=adapter&prettyPrint
> 
> bzw. falls du https verwendest dann natürlich vorne "https", wenn du Authentifizierung für den SimpleAPI Adapter verwendest dann am Ende "&user=username&pass=password dranhängen

File /objects?type=adapter&prettyPrint not found

http://192.168.178.20:8091/objects?type=adapter&prettyPrint

**Comment by peter9teufel** [comment]
der Port muss der sein, der in den Adaptereinstellungen vom SimpleAPI Adapter eingestellt ist

**Comment by sigi2345** [comment]
> der Port muss der sein, der in den Adaptereinstellungen vom SimpleAPI Adapter eingestellt ist

[iob_adapter.txt](https://github.com/user-attachments/files/15721761/iob_adapter.txt)

**Comment by peter9teufel** [comment]
Super danke, damit kann ich den Fehler bei mir reproduzieren, muss ich mir genauer anschauen wie das zustande kommt.

**Comment by sigi2345** [comment]
> Super danke, damit kann ich den Fehler bei mir reproduzieren, muss ich mir genauer anschauen wie das zustande kommt.

Ok, mein System:

Plattform: Windows
RAM: 15.9 GB
Admin: 6.17.14 Port: 8091
Node.js: v20.14.0
NPM: 10.7.0
JS: 5.0.19
Simple-api: 2.8.0  Port: 8090
Socketio: 6.7.0  Port: 8086
Web: 6.2.6  Port: 8095
IOB Mobile: 1.0.2
Handy: Samsung Galaxy A34 5G
Android: 14

**Comment by peter9teufel** [comment]
guter Punkt, App Version bau ich ein.

Das Adapterproblem hab ich glaub ich schon gefunden, muss noch testen aber denke mal kann bis heute Abend online gehen

**Comment by sigi2345** [comment]
Danke, funktioniert.
