### ISSUE TITLE
Feature-Request: Kachel Navigation und PopUp

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#20]
Hallo, 
wenn ich auf eine Kachel klicke auf eine bestimmte Seite springen.
Oder ein Popup aufgeht?

LG
Sigi

**Comment by peter9teufel** [comment]
Hi, da bräuchte ich mehr Infos was genau du meinst, eine Seite innerhalb der App oder eine URL öffnen? Und was wäre genau in dem Popup, URL? Und wäre das Popup somit Fullscreen und nicht einfach nur ein Dialog?
Lg

**Comment by sigi2345** [comment]
> Hi, da bräuchte ich mehr Infos was genau du meinst, eine Seite innerhalb der App oder eine URL öffnen?

App

 Und was wäre genau in dem Popup, URL? Und wäre das Popup somit Fullscreen und nicht einfach nur ein Dialog? Lg

Das wäre für einen Detailansicht als Info als Dialog

**Comment by peter9teufel** [comment]
Innerhalb der App weiternavigieren per Kachel muss ich mir überlegen weil ja die Basis für eine Kachel immer ein Datenpunkt ist. Also mit einem darunterliegenden Datenpunkt ists kein Problem, ohne einem Datenpunkt im Hintergrund ists eine größere Baustelle.

Bezüglich Popup -->genau, es kommt eine Kachel die mehrere DPs anzeigen kann, sollte nicht mehr zu lange dauern.

LG

**Comment by sigi2345** [comment]
> Innerhalb der App weiternavigieren per Kachel muss ich mir überlegen weil ja die Basis für eine Kachel immer ein Datenpunkt ist. Also mit einem darunterliegenden Datenpunkt ists kein Problem, ohne einem Datenpunkt im Hintergrund ists eine größere Baustelle.
> 
> Bezüglich Popup -->genau, es kommt eine Kachel die mehrere DPs anzeigen kann, sollte nicht mehr zu lange dauern.
> 
> LG

Ok, Use Case:

Ich habe die Startseite Home, dort sind alle wichtigen Infos. Am Beispiel Sind alle Fenster offen? sehe ich den DP als Ja/Nein
Jetzt möchte ich sehen welche Fenster offen sind. (Ist ein Skript)

Da gibt es jetzt mehrere Möglichkeiten:

1. Klick auf die Kachel, und es wird mir angezeigt welche als PopUp
2. Klick auf die Kachel und es springt zu einer eigenen Seite
3. Es kommt eine Kachel die mehrere DPs anzeigen kann

Wenn 3 kommt erledigt sich Punkt 1+2

**Comment by peter9teufel** [comment]
Ah ok, ja das macht natürlich Sinn. Ich werd eine Option ergänzen für DP Typen die normalerweise nichts triggern (Einzelwert, Boolean Wert, usw.) dass diese zu einer anderen Seite innerhalb der App navigieren können, der Use Case ist gut.

Außerdem bin ich grad dabei den Typ zu bauen der Kacheln mit mehreren Werte ermöglicht, das wäre aber eher für so Dinge wie Temperatur und Luftfeuchtigkeit von einem Sensor auf einer Kachel kombinieren.

LG

**Comment by AntiHeld889** [comment]
finde ich eine gute Idee, habe ich auch schon drüber nachgedacht

**Comment by peter9teufel** [comment]
Hi!
Hab gerade das Update für Version 1.0.15 eingereicht, sobald es von Apple und Google gerpfüt und freigegeben ist sollte es im Laufe des Tages in den App Stores verfügbar sein.

Beim DP Typen die von sich aus nichts triggern sondern nur anzeigen (Einzelwert, Bild, Tür/Fensterkontakt, Text) kann in der DP Konfiguration jetzt eine Option aktiviert werden, dass zu einer anderen Seite navigiert werden soll, dabei können auch Unterseiten ausgewählt werden, es wird dann direkt zur jeweiligen Hauptseite navigiert und der richtige Tab ausgewählt.

Damit sollte sich dein Use Case jetzt abbilden lassen.

Im Google Play Store sollte das Update in den nächsten Stunden verfügbar sein (im Normalfall 2-3 Stunden), bei Apple dauert es gerne etwas länger bis die Überprüfung durch ist, aber ich gehe mal davon aus dass das Update auch da bis zum Abend, spätestens morgen früh online sein müsste.

LG,
Peter
