### ISSUE TITLE
Datenpunkte werden Teilweise nicht geladen 

### ISSUE THREAD

**Issue by Xells1984** [peter9teufel/iobmobile-issues#23]
Hi,

Vielen Dank für die praktische App. Ich richte mich gerade ein :)

Ich habe gerade versucht Linux Control die fünf Datenpunkte einzurichten. 2 der Punkte werden immer nicht geladen. Lösche ich nochmal alle und füge sie wieder zu, dann sind es nicht immer die selben Datenpunkte die nicht Funktionieren. 

![IMG_7463](https://github.com/user-attachments/assets/0a8998fa-948e-4233-a5d6-3d4bd60b0b13)

Gruß

**Comment by peter9teufel** [comment]
Danke für den Hinweis, schaue ich mir an 👍
Lg

**Comment by peter9teufel** [comment]
Hi nochmal,
habs jetzt mal durchgetestet und den Linux Control Adapter für meinen Mediacluster konfiguriert, hab 9 Datenpunkte konfiguriert und die werden ganz normal geladen, ich schaffs nicht den Fehler nachzustellen. Kannst du mal mehr Details schreiben welche Datenpunkte zu da konkret konfiguriert hast vom Linux Control Adapter und wie die Konfiguration für diese in der App aussieht? Eventuell schaff ichs mit mehr Details das Problem nachzustellen.

![Bildschirmfoto 2024-07-14 um 15 09 55](https://github.com/user-attachments/assets/3275a5c3-f465-4e61-889b-838e23b914cc)


LG,
Peter

**Comment by Xells1984** [comment]
Hi Peter,

Folgende habe ich hinzugefügt:
![IMG_7473](https://github.com/user-attachments/assets/5b11f076-bf07-45e9-b0d1-383c32a420b3)


Betroffen sind Herunterfahren und Upgrade.

Auch beim einzeln hinzufügen das gleiche Verhalten. Ich hoffe das hilft weiter.

Gruß

**Comment by Xells1984** [comment]
Als Taster lassen sie sich Anzeigen. Problem ist wahrscheinlich das dort wie im Screenshot (Null) steht.

**Comment by peter9teufel** [comment]
Jop, das wär auch mein Verdacht dass die Null Werte das Problem sind. Danke für die Info, da hab och einen guten Punkt um es weiter zu untersuchen und zu beheben. Ich geb Bescheid.

Lg

**Comment by peter9teufel** [comment]
Hallo nochmal,
liegt tatsächlich daran, dass die Werte der DP "Null" sind, das ist jedoch nicht zu unterscheiden von normalen Datenpunkten bei denen auf das Laden des Wertes noch gewartet wird und deren Wert nicht Null sein kann. Ich hab jetzt eine zusätzliche Option eingebaut "Wert kann Null sein", wenn die für einen DP aktiviert ist, akzeptiert das Dashboard dass da nix anderes daherkommt und bleibt nicht in der Ladeanimation hängen.

Update Version 1.0.17 mit der Änderung sollte im Laufe des Tages online gehen.

LG,
Peter

**Comment by Xells1984** [comment]
Danke für das Feedback und das fixen 👍

**Comment by peter9teufel** [comment]
Hallo,
Version 1.0.17 ist jetzt verfügbar.

LG,
Peter
