### ISSUE TITLE
Feature Button Art

### ISSUE THREAD

**Issue by Xells1984** [peter9teufel/iobmobile-issues#24]
![IMG_7464](https://github.com/user-attachments/assets/1eb58c50-82cf-4f55-b636-5715e9dced39)

Hi,

Ich habe für  Ventilationsmodi 0-5. Ich würde gerne Ähnlich wie bei den Anzeige Button mit  mehren Werten einen Schalter wo ich mehre Werte mit Text setzen kann.

Ventilatotionsmodus
0 Normal
1 Aus
2 Reduziert
3 erhöht 
4 Maximal 

Wäre das möglich?

Gruß

**Comment by peter9teufel** [comment]
Du möchtest quasi die möglichen Werte die gesetzt werden können in der DP Konfiguration hinterlegen und beim Tippen auf die Kachel aus den vorher festgelegten Werten einen auswählen, hab ich das richtig verstanden?

Lg

**Comment by Xells1984** [comment]
Moin,

Ganz genau. Das wäre perfekt :)

LG

**Comment by peter9teufel** [comment]
Hallo,
Version 1.0.17 ist jetzt verfügbar, ab dieser geht beim Typ "Eigenen Wert schreiben" folgendes:

- beim Wert der geschrieben werden soll können in der Konfiguration vom DP jetzt mehrere Werte mit Beistrich getrennt eingegeben werden
- wenn mehrere Werte so eingegeben werden, müssen zusätzlich Namen für die Werte angegeben werden (ebenfalls komma-separiert)
- wenn du dann auf die Kachel klickst, kommt ein Popup in dem du einen der vordefinierten Werte anklickst damit dieser gesendet wird

LG,
Peter

**Comment by Xells1984** [comment]
Guten Morgen,

Gleich getestet und für gut empfunden 👍
Besten Dank 😬

Gruß

**Comment by peter9teufel** [comment]
Perfekt, freut mich! 😁
Lg
