### ISSUE TITLE
Keine Adapter gefunden.

### ISSUE THREAD

**Issue by DirtyAtze** [peter9teufel/iobmobile-issues#25]
Ich bin gerade dabei, die App zum ersten Mal einzurichten.

leider bekomme ich auf dem Tab 'Adapter' nur die Meldung: keine Adapter gefunden' angezeigt.

Ich habe socketIO und simpleAPI wie [hier](https://github.com/peter9teufel/iobmobile-issues/issues/17#issuecomment-2209264735) beschriebrn eingerichtet, habe auch schon versucht, die Ports in den Adaptern und in der App zu ändern um eventuelle Konflikte zu vermeiden, abner auch das hilft nicht. Außerdem habe ic hbeide Adapter auch schon deinstalliert und neu installiert. Habe auch versucht, die WEB.o instanz zu stoppen aber auch dann bekomme ich in der App keine Adapter angezeigt.
#
Auch issue#17 hilft mir nicht weiter, da ich in den Einstellungen die IP ohne Port eingegeben habe.

Wenn ich http://192.168.178.6:8087/objects?type=adapter&prettyPrint im Browser aufrufe, bekomme ich eine sehr umfangreiche Ausgabe, egal ob am PC oder am Handy.

Ich hänge die Ausgabe, sowie eine Liste der installierten Adapter mit an.

Edit: die Verbindung zu ioB scheint grundsätzlich zu bestehen, die App bringt zumindest keine Fehlermeldung.
Auch die MQTT Verbindung funktioniert und es werden Werte an den ioB gesendet.

IoBroker läuft auf einem NUC unter Proxmox.

Gruß

[Adapter.txt](https://github.com/user-attachments/files/16201595/Adapter.txt)
[PrettyPrint.txt](https://github.com/user-attachments/files/16201606/PrettyPrint.txt)

**Comment by peter9teufel** [comment]
Hi! Danke fürs Anhängen der Daten, ich sehs mir an wenn ich zum Rechner komme 👍
Lg

**Comment by peter9teufel** [comment]
Hi,
konnte den Fehler schon finden, liegt am blackroad Adapter (Eisstraße), der schickt das Feld "title" auch mehrsprachig, das hatte ich bisher bei keinem der Adapter in der Art. Hab den Fehler schon behoben und ein Bugfix Update (Version 1.0.16) eingereicht, sollte in den nächsten Stunden im Play Store verfügbar sein, bei Apple dauert die Prüfung gern etwas länger, da kanns sein dass es erst morgen im App Store ist. Mit Version 1.0.16 sollten die Adapter dann korrekt geladen werden.

Sorry für die Umstände, hoffe das Update wird flott freigegeben, damit du weitermachen kannst 🙂 

LG,
Peter

**Comment by DirtyAtze** [comment]
Super, danke für die schnelle Antwort und den genialen Support!

Wenn alles läuft werd ich auf jeden Fall die Pro-Version upgrade!

**Comment by peter9teufel** [comment]
Das freut mich natürlich 😊 vielleicht kannst kurz Bescheid geben wenn das Update da ist ob es jetzt bei dir auch klappt 👍
Lg

**Comment by DirtyAtze** [comment]
Das Update ist installiert und läuft. Funktioniert alles wie es soll! Danke nochmal für die schnelle Bearbeitung!
