### ISSUE TITLE
Datenpunkt Typ Slider

### ISSUE THREAD

**Issue by Helmut1895** [peter9teufel/iobmobile-issues#26]
Beim Datenpunkt Typ Slider speichert er in den Einstellungen dazu nicht die geänderten Minimum/Maximum Werte. Meim nächsten Aufruf stehen wieder die Werte 0.0 und 100.0 drin.

**Comment by peter9teufel** [comment]
Danke für den Hinweis, da hat sich in der Tat ein Bug eingeschlichen, beheb ich :+1:

LG,
Peter

**Comment by peter9teufel** [comment]
Hallo,
Bug ist gefixt, Update Version 1.0.18 ist eingereicht zur Prüfung, im Play Store sollte es in Kürze verfügbar sein, bei Apple dauert es gern etwas länger, schätze aber im Laufe des Tages sollte es im App Store online gehen.

Danke nochmal für den Hinweis!

LG,
Peter

**Comment by Helmut1895** [comment]
Hallo Peter, 

Tolle Arbeit, weiter so! 

Gruß
H.

**Comment by Helmut1895** [comment]
Hallo Peter,

leider noch nicht so ganz in Ordnung. Werte speichern funktioniert jetzt aber die Anzeige der Scala noch nicht. (siehe Screenshot)
![Slider-Scala](https://github.com/user-attachments/assets/f919e684-1525-4062-a92a-c95010e2fd11)

Gruß
H.

**Comment by peter9teufel** [comment]
Ah, stimmt, das hatte ich nicht auf dem Schirm, dass der Slider natürlich auch für sehr wenige Werte verwendet werden könnte, hab das immer nur mit Bereiche wie 0-50, 0-100, usw. in der Größenordnung getestet. Schau ich mir an, dass das mit wenigen Werten auch ordentlich geht.

LG,
Peter

**Comment by Helmut1895** [comment]
Ich habe den Bereich 5 - 30 eingestellt. Ist ein Heizkörperthermostat.

Gruß
H.

**Comment by peter9teufel** [comment]
Hi!
Neue Version ist schon verfügbar, der Slider sollte für dich jetzt so konfigurierbar und nutzbar sein.

LG,
Peter

**Comment by Helmut1895** [comment]
Hallo Peter,
schau mal, 


![Skalen](https://github.com/user-attachments/assets/3990aed4-1bfa-4b91-ad33-2c95290d7109)

Jetzt ist die 2. Skala (0-100) ein bisschen unleserlich.

LG
H.

**Comment by peter9teufel** [comment]
Eieieiei, sorry, na dann noch ein Anlauf 😄 ich geb Bescheid.

LG,
Peter

**Comment by HackyPaddy** [comment]
Der Slider hat noch eine Störung. Wenn man den Wert einstellen will, bewegt sich der Schieberegler nicht. 

Er stellt zwar den Wert ein, springt dann aber direkt auf die Startseite. 

Zudem zeigt er in dem Wertbalken nichts an. Bei mir ist Min. 30 - Max. 800 eingestellt.

Anbei ein Bild:

![IMG_9870](https://github.com/user-attachments/assets/5ef0eb5d-873f-4d12-960e-8bebffcd39c5)

**Comment by HackyPaddy** [comment]
Mir ist noch eine Sache aufgefallen, was eher ein Luxus-Problem ist.
Wenn man den Wert am Slider verstellt, sendet er die Daten ja sofort an den ioBroker.

Bei ner Lampe ist das kein Ding.

Aber ich steuere mit dem Slider z.B. eine PV-Anlage. Wenn ich jetzt die maximale Leistung von 800 Watt auf 500 Watt setze, dann haut er mir duzende Leistungswerte raus, die dann vom Script verarbeitet werden. Sind es zu viele, stürzt der Wechselrichter ab und bootet neu. Unschön...

Kannst Du das so verwirklichen, dass die Werte erst nach einer Beruhigungszeit von 2 Sekunden gesendet werden? Das würde das ganze entzerren.

Ich kann fange das momentan mit dem Script ab, aber für andere User, die nicht so versiert sind, vielleicht eine gute Hilfe.


Viele Grüße

Patrick

**Comment by HackyPaddy** [comment]
Den neuen Slider teste ich morgen, ich bin aktuell nicht vor Ort und wenn das nicht 100%ig läuft, hab ich nen Problem :)

Ich berichte morgen :)

**Comment by HackyPaddy** [comment]
So, ich habe die Funktion mit dem schreiben des Wertes beim loslassen des Sliders getestet. Funktioniert prima!
Deutliche Verbesserung zu vorher.

Dabei kam mir noch ne Idee:

Wenn ich jetzt einen Slider den Wertebereich von bspw. 0-500 gebe, dann ist das ein "Rätselraten", welcher Wert gerade gewählt wird. Dieser wird nämlich erst angezeigt, wenn der Slider wieder losgelassen wird.

Deshalb ne Idee zur Verbesserung:

Kannst Du das so integrieren, dass man den Ziel-Wert schon bei der Bestätigung des Sliders sehen kann. Als Tooltip oder oben, wo der aktuelle Wert steht?

**Comment by peter9teufel** [comment]
Aber klar doch, war eigentlich ohnehin geplant ist mir aber dann irgendwie entfallen 😄
Habs schon eingebaut, beim Slider mit Beschriftung wird einfach direkt der Wert darüber aktualisiert, beim Slider ohne Beschriftung kommt ein kleinens Popup mit dem Wert solange der Slider bewegt wird.

Kommt im nächsten Update.

Danke für den Hinweis!
LG,
Peter

**Comment by peter9teufel** [comment]
Update Version 1.0.26 mit den Slider Anpassungen ist schon online 👍 

LG

**Comment by HackyPaddy** [comment]
Gleich heute Nacht getestet, war wohl der erste, der das Update geladen hat :)
Hab den Slider nun in allen erdenklichen Formen und Funktionen getestet.

Alles perfekt!

Leider kann ich den Case nicht schließen, das musst Du machen...

Viele Grüße

Patrick

**Comment by peter9teufel** [comment]
Wunderbar, danke für die Unterstützung, allein kommt man ja gar nicht auf all die Use Cases 😄 

Dann mach ich hier zu 👍
