### ISSUE TITLE
Automatische Aktualisierung von Werten

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#27]
Moin :)

Für ein nächstes Release der App wäre es klasse, wenn man einstellen kann, dass sich bestimmte Werte automatisch aktualisieren lassen, z.B. bei jedem neuen Wert im ioBroker oder nach einer fest einstellbaren Zeitspanne, z.B. 10 Sek.

Wenn man jetzt Werte kontrollieren will, muss man immer die Seiten wechseln, damit er die neuen Werte empfängt.

Viele Grüße

**Comment by peter9teufel** [comment]
Hi!
Bei welchem Datenpunkt Typ ist das so bei dir? Die Kacheln sind per SocketIO mit dem ioBroker verbunden, somit kommt jede Änderung eines Wertes rein und wird auch in der UI aktualisiert. Hab das gerade nochmal getestet mit ein paar Datenpunkten und bekomm die Änderungen live rein in der App. Der einzige Typ wo ich das noch erweitern muss ist der DP Typ "Mehrere Werte", weil hier nur der Datenpunkt der primär konfiguriert wurde über Socket IO aktualisiert wird, die sekundären Datenpunkte aktuell noch nicht soweit ich es jetzt auswendig weiß, das hab ich auf der ToDo.

LG

**Comment by HackyPaddy** [comment]
Der Typ ist ein ganz normaler "Einzelwert".
Wenn ich die Seite offen habe, zeigt er mir den Wert mit Zeitstempel an.

Im ioBroker, den ich nebenbei im Browser auf habe, aktualisiert er fleißig die Werte. In der App bleibt der Wert jedoch stehen, außer ich switche einmal auf eine andere Seite und wieder zurück. Dann wird der aktuelle Wert geladen.

**Comment by peter9teufel** [comment]
Das ist seltsam, hab grad nochmal getestet, sieht man schön bei der Windgeschwindigkeit, da der Wert recht instabil ist, ist ganz normal vom Typ "Einzelwert" und aktualisiert sich laufend, auch der Zeitstempel wird dabei aktualisiert wenn mans lange genug offen lässt.

https://github.com/user-attachments/assets/a07afccc-eb73-47c7-86ad-d04fe73e4c57

Hast du vielleicht konkrete Beispiele von bestimmten Adapter bei denen du das beobachten kannst? Ich kann das beschriebene Verhalten aktuell nicht reproduzieren, vielleicht gelingt es mir doch mit mehr Details.

LG,
Peter

**Comment by HackyPaddy** [comment]
So hätte ich das gerne :)

im ioBroker ist das ein selbst angelegter Datenpunkt unter 0_userdata.
Hier die Objektdaten:

`{
  "common": {
    "name": "Leistung Gesamt",
    "desc": "Ausgangsleistung Wechselrichter",
    "role": "state",
    "type": "number",
    "read": true,
    "write": true,
    "def": 0,
    "unit": "W",
    "custom": {
      "history.0": {
        "enabled": true,
        "aliasId": "PV_Leistung_Gesamt",
        "debounceTime": 0,
        "blockTime": 0,
        "changesOnly": true,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "ignoreBelowNumber": "",
        "disableSkippedValueLogging": false,
        "retention": 0,
        "customRetentionDuration": 365,
        "maxLength": 8000,
        "enableDebugLogs": false,
        "debounce": 0,
        "chartStep": ""
      }
    }
  },
  "type": "state",
  "native": {},
  "_id": "0_userdata.0.Photovoltaik.Leistung_Gesamt",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1721726032280
}`

Dieser Datenpunkt wird von einem Script beschrieben.

**Comment by HackyPaddy** [comment]
https://github.com/user-attachments/assets/de37fb99-34cf-45a8-8729-eb14bd00ca00

**Comment by peter9teufel** [comment]
Das ist in der Tat sehr komisch, hab eigentlich den gleichen UseCase nur dass ich den Gesamtverbrauch anzeige, dieser liegt in einem DP in 0_userdata und wird bei jeder Änderung per Skript geschrieben und auch in der App aktualisiert. Einziger Unterschied den ich sehe ist, dass bei mir der Datenpunkt vom Typ "Zahl" ist. Das Skript schreibt den Wert zudem immer mit "acknowledged = true"

`
setState(ID_TOTAL, value, true);
`

**Comment by HackyPaddy** [comment]
Bei mir das gleiche. Ich schreibe das auch mit einen ACK und der DP ist vom Typ Zahl (number). Also, genau wie bei Dir.

Warum er das bei mir aber nicht automatisch synchronisiert... Hmm..

**Comment by peter9teufel** [comment]
hab gerade auch noch getestet wie in deinem Video den gleichen Datenpunkt in der zweiten Unterseite auch anzuzeigen, keine Änderung, wird ganz normal aktualisiert.

Bin mit meinem Latein grad bisschen am Ende weil ichs einfach nicht schaffe den Fehler nachzustellen 🤔

**Comment by HackyPaddy** [comment]
Ich habe auch gerade nochmal einen frischen Datenpunkt angelegt. Wieder Typ "Zahl" und diesmal aktualisiere ich den per Hand, aber kein Erfolg.

Der Wert wird nicht aktualisiert.

Die Konfiguration ist mit interner IP, Standard-Ports (8087, 8084), ohne HTTPS, aber mit Authentifizierung, ohne MQTT.

**Comment by peter9teufel** [comment]
OK, ich versuche mal die Authentifizierung bei mir auch zu nutzen, vielleicht liegt es daran und ich kanns damit nachstellen. Wird aber etwas dauern, muss jetzt wieder was arbeiten 😄 

Ich geb dir hier Bescheid wenn ich das mit Authentifizierung testen konnte.

LG,
Peter

**Comment by HackyPaddy** [comment]
Geteiltes Leid, ist halbes Leid...
Mach ganz in Ruhe :)

**Comment by peter9teufel** [comment]
Jop, mit Authentifizierung konnte ichs jetzt nachstellen. Ich sehs mir nach der Arbeit an 👍 

Danke für den Hinweis!

LG

**Comment by peter9teufel** [comment]
Fehler gefunden und behoben, ich teste noch, Update werd ich dann voraussichtlich morgen einreichen. Ich geb dir Bescheid 🙂 

LG,
Peter

**Comment by HackyPaddy** [comment]
Moin :)

Update bei Apple ist durch, hab es mir grad gezogen und et voilà -> Es läuft nun :)

Vielen Dank!
