### ISSUE TITLE
On/Off Button mit zwei Datenpunkten

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#28]
Moin Peter,

ich hab gleich nochmal was.
Den ioBroker habe ich auch mit den KNX-System im Haus verknüpft.

Nun ist es bei einigen Aktoren so, dass die einen Datenpunkt für den Zustand haben (True, False); dafür kann man aber nicht schalten.

Und dann gibt es einen Schaltpunkt (True, False).

Wäre das für dich eine große Herausforderung, wenn du in dem On/Off-Button noch die Funktion hinzufügst, dass man einen separaten Schaltpunkt hat?

Du hast es schon bei dem Punkt "Eigenen Wert schreiben" umgesetzt. Nur dieser Typ ist leider ungeeignet für mich.

Viele Grüße

Patrick

**Comment by peter9teufel** [comment]
Hi! Kann ich ergänzen, nachdem es für den anderen Typ schon eingebaut ist sollte sich da eh einiges übernehmen lassen. Ich geb Bescheid.

LG,
Peter

**Comment by HackyPaddy** [comment]
Hab mir grad das Update gezogen.
Es funktioniert perfekt, herzlichen Dank :)

Und wieder hätte ich ne Idee... Du lynchst mich bald :)

Genau dieses Szenario, mit den Datenpunkten wäre auch beim Slider schön. Sprich ein Datenpunkt zum lesen und ein Datenpunkt zum schreiben.

Zudem ist mir beim Slider folgendes aufgefallen:

Wenn im Raster 2x1 oder 2x2 angegeben ist, funktioniert die Wertanzeige mittlerweile perfekt. Ist aber 2x3 oder 2x4 eingestellt, dann stimmt der Wertbalken nicht.

Zudem schmeißt er einen fast endlosen Satz Dezimalzahlen. Stelle ich z.B. 300 ein, kommt im iobroker 300,8328374 an. Als Beispiel jetzt.

Viele Grüße
Patrick

**Comment by peter9teufel** [comment]
> Du lynchst mich bald :)

So schnell geht das nicht, dafür gibts als Schutzschild dann ja das Abo 😉 

> Genau dieses Szenario, mit den Datenpunkten wäre auch beim Slider schön. Sprich ein Datenpunkt zum lesen und ein Datenpunkt zum schreiben.

Das sollte sich recht einfach erweitern lassen, mach ich im nächsten Update 👍 

> Wenn im Raster 2x1 oder 2x2 angegeben ist, funktioniert die Wertanzeige mittlerweile perfekt. Ist aber 2x3 oder 2x4 eingestellt, dann stimmt der Wertbalken nicht.

Schau ich mir an, hab da offenbar übersehen die Tablet Varianten mit mehr Spalten zu testen, danke für den Hinweis.

> Zudem schmeißt er einen fast endlosen Satz Dezimalzahlen. Stelle ich z.B. 300 ein, kommt im iobroker 300,8328374 an. Als Beispiel jetzt.

Ist notiert, ich änder das im nächsten Update damit nicht die exakten Sliderwerte gesendet werden sondern vorher gerundet wird 👍 

LG,
Peter

**Comment by HackyPaddy** [comment]
Perfekt, dann hab ich schon "das Schutzschild" :)

Ich bin gespannt auf die nächsten Updates. Die App wird immer besser :)

**Comment by peter9teufel** [comment]
Sliderwerte sollten ab Version 1.0.23 übrigens schon gerundet werden, also nicht mit unzähligen Nachkommastellen ankommen.

LG

**Comment by HackyPaddy** [comment]
Ich habs gerade mal mit einem manuellen Datenpunkt versucht -> es funktioniert :)
Das andere kann ich leider erst testen, sobald der Slider auch den zusätzlichen Datenpunkt zum schreiben hat.

Was mit aber noch aufgefallen ist, wenn ich eine On/Off Kachel mit dem Attribut "Vor Änderungen schützen" schalten will, sprint der danach wieder auf die Hauptseite. Das macht er bei On/Off Kacheln ohne den Schutz nicht, da bleibt er auf der Seite.

**Comment by peter9teufel** [comment]
Separater DP für Slider kommt mit dem heutigen Update, sollte im Laufe des Tages verfügbar sein.

Dass beim Reload der Seite immer auf den ersten Tab der Hauptseite springt schau ich mir als nächstes an.

LG,
Peter

**Comment by HackyPaddy** [comment]
Sehr gut, ich teste es gleich aus, sobald es online ist.
Ein Fehler beim Slider hab ich noch entdeckt...

Wenn man den Wert in einer anderen Anwendung ändert, dann zeigt er den neuen Wert in Deiner App richtig an. Aber der Schieberegler bleibt an seiner alten Position. D.h. der Slider aktualisiert nur die Hälfte :)

**Comment by HackyPaddy** [comment]
Du bist die Wucht. Es läuft einwandfrei! Danke :)
