### ISSUE TITLE
Hue-Lampen beim RGB-Regler -> Keine Funktion

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#29]
Moin Peter,

ein neues Problem.
Ich wollte gerade eine Hue-Lampe integrieren. RGB-Typ ausgewählt, dann unter RGB Einstellunge den Typ HSV angegeben und wollte nun die Datenpunkte für Hue, Sat., Value und Co einfügen.

Das klappt aber nicht. Es tauchen keine Datenpunkte mehr auf, stattdessen stürzt die Oberfläche vom ioBroker ab.

Getestet auch ohne Authentifikation. Bei beiden Varianten ist der Fehler vorhanden.

Viele Grüße
Patrick

**Comment by HackyPaddy** [comment]
Mir fällt auf, dass er im Log von Socket.io teilweise einen Login ohne Kennwort versucht. Das könnte wohl die Ursache sein...

**Comment by peter9teufel** [comment]
Hmm, das klingt in der Tat seltsam, danke für den Hinweis, schau ich mir an.

LG,
Peter

**Comment by peter9teufel** [comment]
Hallo nochmal,
den Fehler, dass keine Datenpunkte angezeigt wurden die man auswählen kann hab ich gefunden und behoben, Update kommt heute noch.

Das Problem, dass sich alles aufhängt konnte ich nicht nachstellen, über HSV hab ich auf die Schnelle zum Testen nicht sicher gewusst welche Datenpunkte da die entscheidenden sind, über die RGB Datenpunkte mit dem Level DP für die Helligkeit konnte ich eine HUE RGB Lampe aber problemlos konfigurieren.

Probiers mal mit Version 1.0.23 sobald die online ist (sollte im Laufe des Nachmittages verfügbar sein, Apple evt. etwas später).

LG

**Comment by HackyPaddy** [comment]
Sobald die online ist, teste ich und geb Rückmeldung ;)Am 26.07.2024 um 13:27 schrieb Peter 9teufel ***@***.***>:﻿
Hallo nochmal,
den Fehler, dass keine Datenpunkte angezeigt wurden die man auswählen kann hab ich gefunden und behoben, Update kommt heute noch.
Das Problem, dass sich alles aufhängt konnte ich nicht nachstellen, über HSV hab ich auf die Schnelle zum Testen nicht sicher gewusst welche Datenpunkte da die entscheidenden sind, über die RGB Datenpunkte mit dem Level DP für die Helligkeit konnte ich eine HUE RGB Lampe aber problemlos konfigurieren.
Probiers mal mit Version 1.0.23 sobald die online ist (sollte im Laufe des Nachmittages verfügbar sein, Apple evt. etwas später).
LG

**Comment by HackyPaddy** [comment]
Neue Version ist online und Tada, die Auswahl der Datenpunkte funktioniert nun.

Aber mal eine Frage: Was meinst du mit Value? Was soll da übergeben werden?

**Comment by peter9teufel** [comment]
HSV steht für Hue, Saturation und Value, wobei Value der Helligkeitswert der Farbe ist. Habs jetzt mit einer Hue Lampe probiert, aber da klappt irgendwas nicht.

Aber die Hue Lampen bieten ja eh die R,G und B Datenpunkte an, also einfach mal als RGB Typ RGB auswählen, damit klappts problemlos bei mir. Der DP für den Dimmerwert ist bei mir im Hue Adapter der Level Datenpunkt.

LG

**Comment by HackyPaddy** [comment]
Ja genau, da haut irgendwas noch nicht hin...

Ich hab bei meinem
Adapter leider keine Punkte für RGB.

Ich nutze deconz für die Hue-Lampen

**Comment by peter9teufel** [comment]
Gibts evt. einen Color Datenpunkt in dem der Hex-Wert der Farbe steht?

**Comment by HackyPaddy** [comment]
Ne leider auch nicht...
Ich mach dir nachher mal nen PrintScreen der Datenpunkte

**Comment by peter9teufel** [comment]
Jop das wär optimal, ohne HSV Lampe HSV testen is immer a bissl speziell 😅

**Comment by HackyPaddy** [comment]
<img width="1137" alt="Bildschirmfoto 2024-07-26 um 20 34 46" src="https://github.com/user-attachments/assets/9fc122dd-29d9-4534-96e2-ed9be670fb88">

So, hier hast Du mal den Screenshot.
Es sind folgende Datenpunkte wichtig:

1. On = boolean zum Ein- und Ausschalten der Leuchte
2. hue = HSV Farbraum in Grad ° (gute Anleitung findest Du bei Wiki zum HSV)
3. level = Helligkeit von 1% bis 100%
4. sat = Saturation - Ich meine das ist die Intensität der Farben

Der Datenpunkt "bri" ist das gleiche wie Level, nur von 1 bis 254, was 1% bis 100% entspricht. Nutze ich eigentlich nie.

Die anderen Datenpunkte sind irrelevant.

Hilft Dir das?

**Comment by HackyPaddy** [comment]
https://learn.leighcotnoir.com/artspeak/elements-color/hue-value-saturation/

**Comment by peter9teufel** [comment]
Hi,
also HSV wäre **H**ue, **S**aturation und **V**alue (auch Lightness, Brightness). Value ist somit in dem Anwendungsfall unnötig weil durch den DP für die Helligkeit eh schon abgedeckt.

Habs jetzt angepasst, dass nur Hue, Saturation und Helligkeit konfiguriert werden müssen, hab leider nicht genau deinen Fall zum Testen. Bei meiner RGB Lampte (über den Zigbee Adapter) muss der Farbwechsel zusätzlich in einen separaten Datenpunkt mit reingeschrieben werden, der heißt bei mir "Payload" und dient dazu Befehle zu schicken. Den kann man jetzt auch konfigurieren, ist aber optional, wenns ohne dem geht dann gut, wenn nicht könnte das in deinem Screenshot zB. der "action" DP sein.

Update 1.0.24 ist eingereicht und sollte im Laufe des Tages verfügbar werden, probiers damit mal und gib Bescheid. Ist etwas ins Blaue hinein weil ich leider exakt deinen Fall nicht testen kann 😄 

LG,
Peter

**Comment by HackyPaddy** [comment]
Ich berichte :)

**Comment by HackyPaddy** [comment]
So, gerade getestet. Deutlich besser als vorher.
Er erkennt nun die Farben, wenn sie in einer anderen App oder im ioBroker geändert wurden, er schreibt alles richtig.

Allerdings: Hue ist mal wieder ein Spezialfall. Die Saturation geht nicht von 1-100, sondern von 1-255. Wobei 255 = 100% entspricht.

Ansonsten funktioniert der Regler perfekt :)

**Comment by peter9teufel** [comment]
Oh Mann, die Hue tun mir was an 😂 Ich denk mal da gibts dann sicher andere RGB Lampen bzw. Adapter wo der Wertebereich von 0-100 geht. Ich erweiter es um eine Option damit man auswählen kann ob der Wertebereich von 1-100 geht oder von 1-254, dann bleibts flexibel.

Danke für den Hinweis, schön langsam kriegen wir die HSV Lampe in den Griff 😄

**Comment by HackyPaddy** [comment]
Macht doch Spaß oder?

Ich kenn das mit der Range von 0-254 auch nur von Hue-Lampen so. 

Wenn man als Hersteller groß genug ist, kann man sich solche Spielchen erlauben.

Ich würde den Punkt erweiterte Saturation nennen. Ich denke nämlich, es gibt bestimmt Adapter die diese Hue-Eigenschaft intern umsetzen und dann nur der Wertebereich von 0-100 angegeben werden muss.

**Comment by HackyPaddy** [comment]
Funktioniert nun aller erste Sahne. Genial :)

Ich schließ das mal -> das Thema "Hue" hätten wir gemeistert

**Comment by peter9teufel** [comment]
Halleluja 😄 
freut mich, dass es jetzt klappt 👍
