### ISSUE TITLE
Gerät: Yamaha MusicCast 

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#3]
Hallo,

das Gerät (Adapter) Musiccast funktioniert leider nicht.
Die DP sind zwar sichtbar, aber es wird nichts übernommen.

https://github.com/foxthefox/ioBroker.musiccast

LG
Sigi

**Comment by peter9teufel** [comment]
OK, das wird ein bisschen ein Trial and Error Prozess werden, hab selber keine MusicCast Geräte von Yamaha und der günstigste Lautsprecher ist mit 189 kein Schnäppchen um den nur fürs debuggen zu kaufen 😄  Ich mach mich mal schlau.

LG

**Comment by sigi2345** [comment]
> OK, das wird ein bisschen ein Trial and Error Prozess werden, hab selber keine MusicCast Geräte von Yamaha und der günstigste Lautsprecher ist mit 189 kein Schnäppchen um den nur fürs debuggen zu kaufen 😄 Ich mach mich mal schlau.
> 
> LG

Brauchst du die DP als Json?

**Comment by peter9teufel** [comment]
das wär ein Ansatz, vielleicht kann ich damit was erreichen, schicks mal durch, besser als nichts 🙂

**Comment by sigi2345** [comment]
> das wär ein Ansatz, vielleicht kann ich damit was erreichen, schicks mal durch, besser als nichts 🙂

[musiccast.json](https://github.com/user-attachments/files/15719335/musiccast.json)

**Comment by sigi2345** [comment]
Hallo,

es würden schon diese DP genügen:

![Screenshot (814)](https://github.com/peter9teufel/iobmobile-issues/assets/41079106/76fda518-fa39-490a-a2fd-0f56085fc512)

**Comment by sigi2345** [comment]
Ok, mit Version 1.0.6 funktionieren die DP bis auf das URL Problem.

DP:
musiccast.0.RX-V481_.netusb.albumart_url

Flexibler Wert:
http://192.168.178.25/YamahaRemoteControl/AlbumART/AlbumART9568.jpg

RAW:

`{
  "type": "state",
  "common": {
    "name": "albumart url",
    "type": "string",
    "read": true,
    "write": false,
    "role": "text",
    "desc": "albumart url"
  },
  "native": {},
  "from": "system.adapter.musiccast.0",
  "user": "system.user.admin",
  "ts": 1701955917316,
  "_id": "musiccast.0.RX-V481_.netusb.albumart_url",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

![Screenshot (845)](https://github.com/peter9teufel/iobmobile-issues/assets/41079106/ce070822-aa5f-49bb-b329-96b1a1fa814f)

**Comment by sigi2345** [comment]
Funktioniert mit V 1.0.9
