### ISSUE TITLE
Auswahl bei Datenpunkte ob Ack-Flag gesendet werden soll

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#30]
Moin Peter,

eine weitere Idee.
Was hältst Du davon, wenn man in den Datenpunkten auswählen kann, dass zusätzlich ein ACK-Flag gesetzt werden soll?

Ich hab z.B. Datenpunkte im ioBroker, die nur mein Wunsch darstellen sollen. Die werden in Scripten zwar verarbeitet, aber meist fehlt dort das Ack-Flag.

Da wäre es toll, wenn man das direkt beim Betätigen übergeben kann.

**Comment by peter9teufel** [comment]
Hi,
hab ich gleich in meine ToDo Liste aufgenommen, guter Punkt.

LG,
Peter

**Comment by HackyPaddy** [comment]
Gerade ein Test durchgeführt...

Sauber, klappt einwandfrei. Danke :)
