### ISSUE TITLE
Farben umkehren beim Fenster-/Tür Datenpunkt

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#31]
Moin Peter,

ich bastel gerade wieder rum und dabei ist mir noch eine Sache aufgefallen.
Bei dem Fenster-/Türen-Datenpunkt wird true und false als Farbe dargestellt.

Rot = false
Grün = true

Nun ist es aber so, dass meine Datenpunkte im ioBroker true als Offen melden und false als geschlossen.

Da wäre es doch klasse, wenn Du eine Option zur Umkehrung der Farben hinzufügst. 

Dann würde es folgende Konstellation geben:

Rot = true
Grün = false

Viele Grüße

Patrick

**Comment by peter9teufel** [comment]
Guter Punkt, es ist langfristig ohnehin geplant, dass man die Farben für true/false evt. auch selbst auswählen kann, das würde dann auch diesen Fall abdecken,wird aber eher erst gegen Ende kommender Woche live gehen können.

LG,
Peter

**Comment by HackyPaddy** [comment]
Wenn Du das eh schon auf der Agenda hast, dann noch besser :)
Willst Du das denn bei allen in Frage kommenden Punkten machen?

**Comment by peter9teufel** [comment]
Geplant ist generell die Icon Farbe einstellbar zu machen, bei allen DP die true/false liefern zusätzlich eine zweite Farbe, also ja, generell für alle passenden DP Typen 👍

**Comment by HackyPaddy** [comment]
Mega :) Dann bin ich mal gespannt 👍

**Comment by HackyPaddy** [comment]
Auch hier, funktioniert prima!
Bei den Icons, sowie auch bei Textfarben.

Alles bestens -> close :)
