### ISSUE TITLE
Appstart mit Authentifizerung lädt Daten nicht

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#32]
Moin Peter,

ich weiß nicht, ob das Verhalten vor dem Update schon so war, aber seit dem Update auf 1.0.24 lädt er die Daten nicht, wenn die App gestartet oder aus dem Hintergrund geholt wird.

Die Kreise drehen sich und drehen sich und drehen sich. Wechselt man einmal auf eine andere Seite, dann holt er die Daten.

Hier ein Video...

https://github.com/user-attachments/assets/25f8071e-e307-4c3f-9169-8b5b45160875

Ohne Authentifizierung lädt er die Daten sofort...

Viele Grüße

Patrick

**Comment by HackyPaddy** [comment]
Mir ist auch aufgefallen, dass im
Log voM ioBroker immer noch Einträge vom socket.io auftauchen, wo trotz eingeschalteter Authentifizierung kein Wort übergeben wird.

Da muss im Code noch irgendwas faul sein.

**Comment by peter9teufel** [comment]
Hi! Sorry, war etwas stressig diese Woche, bin gerade dabei mir das anzusehen, kanns aber nicht wirklich reproduzieren. Hab heute ein Update geplant, werd versuchen den Fehler noch nachzustellen damit ich dem auf die Schliche kommen kann was es da hat.

Welche Log Einträge genau siehst du die ohne Authentifizierung übergeben werden?

**Comment by HackyPaddy** [comment]
Hey :)

Kein Ding, kenn ich ja selber.
Ich habe mir das Update mal gezogen. Das Problem mit der Authentifizierung besteht weiterhin noch.

Test ohne Authentifizierung: Alles perfekt!
Test mit Authentifizierung: Klappt nicht...
Test mit Authentifizierung, aber mit Passwort ohne Sonderzeichen: Klappt auch nicht...

Es liegt also nicht an den Sonderzeichen im Passwort, wie es damals mal der Fall war.

Im Log vom ioBroker stehe ich, dass er sich unter dem admin und dem Passwort einloggt. Kurz danach loggt er sich nochmal als admin ein, aber diesmal ohne Passwort und genau daran wird es liegen. Irgendwo wird ein Passwort nicht übertragen und die Authentifizierung scheitert.

Auf der Seite sind folgende Datenpunkte:

1. Datenpunkt mit Boolean Wert
2. Datenpunkt Einzelwert
3. Datenpunkt Einzelwert

Vielleicht hilft Dir das bei der Fehlersuche :)


Viele Grüße

Patrick

**Comment by HackyPaddy** [comment]
Hier noch das Log vom ioBroker:


socketio.0 | 2024-08-04 16:33:12.472 | debug | socket.io client admin connected
-- | -- | -- | --
socketio.0 | 2024-08-04 16:33:12.471 | debug | Logged in: admin
socketio.0 | 2024-08-04 16:33:12.282 | debug | Logged in: admin, *********
socketio.0 | 2024-08-04 16:33:12.258 | info | ==> Connected system.user.admin from ::ffff:192.168.1.87

**Comment by peter9teufel** [comment]
sehr seltsam, ist unter iOS oder?

Werd ich wohl mal mein produktives System im Haus auf Authentifizierung umstellen, eventuell lässt es sich mit den echten Dashboards nachstellen, muss ich halt mal einen ruhigen Moment abwarten in dem keiner da ist 😄

**Comment by HackyPaddy** [comment]
Nur iOS ist das Wahre 😆 

Ich merk sofort den Unterschied, wenn die Authentifizierung aus ist. Die App ist dann auch deutlich schneller.

Du kannst das ganz einfach testen. Mal ne zweite Instanz von socket.IO und der simple.Api und die Adapter stellst auf Authentifizierung.

Dann musst nix groß umstellen und kannst das produktiv testen.

Mach ich genauso :)

**Comment by HackyPaddy** [comment]
Moin Peter,

konntest Du das Problem eingrenzen?
Oder doch schwieriger als gedacht?

Viele Grüße

Patrick

**Comment by peter9teufel** [comment]
Hi,
war jetzt mit Urlaub und ein paar Erweiterungen blockiert, sehs mir als nächstes nochmal an 👍

Lg

**Comment by peter9teufel** [comment]
Hi!
Hab grad nochmal 2 Stunden versucht den Fehler zu finden 😄 konnte ihn dann auch mal reproduzieren und hab jetzt noch Kleinigkeiten angepasst die mglw. das Problem lösen. Ich schaffte es zumindest nicht mehr, nach den Änderungen den Fehler zu erzeugen.

Hab ein Update (Version 1.0.31) eingereicht, dass nur diese Änderungen enthält. Teste bitte nochmal sobald 1.0.31 verfügbar ist.

LG,
Peter

**Comment by peter9teufel** [comment]
Hi nochmal,
Update (Version 1.0.31) sollte in den Stores jetzt schon verfügbar sein.

LG,
Peter

**Comment by HackyPaddy** [comment]
Du hast es geschafft! 😁

Wenn ich den Adapter socket.io auf Debug stelle, sehe ich zwar, dass er sich manchmal immer noch versucht, ohne Benutzer bzw. ohne Kennwort anzumelden, aber die App läuft. Auch, wenn ich diese aus dem Hintergrund hole.

Vielleicht schaust bei ner umfangreichen Wartung nochmal, ob da irgendwie noch die Authentifizierung fehlt bzw. die Logindaten nicht korrekt übermittelt werden.

Aber ich bin zufrieden. Nächste Stufe ist jetzt das https, damit ich von aussen zugreifen kann. Ich berichte :)


Lg
Patrick

**Comment by peter9teufel** [comment]
Das ist scheinbar eine Eigenheit vom Logging des Adapters, Authentifizierung wurde eh schon immer bei jedem Call mitschickt, war nur ein sehr spezielles Timingproblem in Kombination mit Auth das ich gefunden habe.

Super, dass es jetzt funktioniert 👍 sollte wieder was auftreten einfach wieder ein Issue aufmachen 😁

Lg, Peter
