### ISSUE TITLE
Bindings bzw Berechung zweier Datenpunkte

### ISSUE THREAD

**Issue by DickenSerm** [peter9teufel/iobmobile-issues#33]
Hey, bei meiner VIS auf dem Tablet nutze ich Bindings wo ich mir zbsp direkt das Ergebnis von "Datepunkt1 - Datenpunkt2" anzeigen lasse.

Es wäre cool wenn man hier auch die Möglichkeit zu rechnen hätte.

LG
Dicken

**Comment by peter9teufel** [comment]
Hi,
grundsätzlich nicht unmöglich hab aber grad keine Idee wie ich das einfach bedienbar einbauen würde 😄  solche Dinge sind halt über eine WebUI einfacher umsetzbar. Vorerst wirds mal nötig sein, die Berechnungen mit Blockly/Javascript zu machen und in einem Datenpunkt in 0_userdata abzulegen für die Anzeige.

LG,
Peter

**Comment by DickenSerm** [comment]
Ok, sowas hab ich mir schon gedacht :) Das mit dem Datenpunkt geht ja immer. Dann würde ich das hier mal wieder zu machen.
