### ISSUE TITLE
Boolean status mit Trigger verknüpfen

### ISSUE THREAD

**Issue by loemic87** [peter9teufel/iobmobile-issues#35]
Hallo,

erstmal: danke für die App! Das ist eine Offenbarung!

Am Beispiel meiner Steuerung für ein Garagentor möchte ich einen Vorschlag machen:

Ich habe einen Sensor der feststellt, ob das Tor offen oder zu ist. Der gibt true/false aus. Das auszulesen und darzustellen klappt mit "Boolean status" wunderbar. 
Über einen Druck auch diese Kachel würde ich gerne das Tor aber auch öffnen können. Das wäre wiederum ein anderer DP der auf true gesetzt werden müsste.

Ist das möglich?

Danke für deine Arbeit! Abo wird sicher gebucht

**Comment by peter9teufel** [comment]
Hi!
> erstmal: danke für die App! Das ist eine Offenbarung!
danke, das hört man gerne 🙂 

Ich überleg mir dazu was, sinnvoll wäre aber vermutlich, wenn man sowohl true als auch false senden könnte oder?

LG,
Peter

**Comment by loemic87** [comment]
Ja, da wäre true/false sinnvoll. Je nachdem, wie man es braucht. Kann ja auch als Taster fungieren.

**Comment by santa81** [comment]
@peter9teufel 
Vielleicht wäre es generell sinnvoll, widgets miteinander verbinden zu lassen?
könnte mir als usecase auch vorstellen,  Leistung von einem Gerät mit dazugehörigen Schalter. In dieser Form könnten viele sensoren mit passenden Schalter kombiniert werden .

**Comment by peter9teufel** [comment]
Klingt nicht schlecht, werd mir diesbezüglich was überlegen.

LG,
Peter

**Comment by peter9teufel** [comment]
Hallo,
1.0.28 ist im Play Store, Apple prüft das Update aktuell noch.

Für die Typen "Einzelwert", "Mehrere Werte", "Tür/Fenster Kontakt", "Boolean Status" und "Text" kann jetzt ein On/Off Trigger Datenpunkt konfiguriert werden, bei Klick auf die Kachel kann in diesen dann via Popup true/false geschrieben werden.

LG,
Peter
