### ISSUE TITLE
Swipe um zwischen Seiten zu wechseln

### ISSUE THREAD

**Issue by loemic87** [peter9teufel/iobmobile-issues#36]
Der Titel sagt es bereits. Ich erwische mich dabei, wie ich Versuche, nach rechts/links zu swipen um die Seiten zu wechseln.  
Kann man das (ggfls optional) mit einbauen?

**Comment by peter9teufel** [comment]
Hi,
das wurde schon mal gewünscht, was dabei noch etwas tricky sein könnte bzw. inkosistent in der Usability ist der Swipe in Zusammenhang mit Unterseiten. Wenn Unterseiten vorhanden sind, werden diese ja als Tabs dargestellt. Bei Tabs ist der Swipe der Standard um zwischen den Tabs zu wechseln, was dann damit kollidiert den Slide für etwas anderes zu verwenden.

Ich schau mir das mal an, eventuell kann ichs mal für Seiten die keine Unterseiten als Tabs haben ergänzen, eventuell wenn Tabs vorhanden sind dann nur am ersten und letzten Tab den Swipe für Seitennavigation nutzen (wenn das möglich ist).

Schau ich mir an.

LG,
Peter

**Comment by loemic87** [comment]
Ah okay, habe bisher nur eine Unterseite unterhalb einer Seite mit wenig Inhalt. Da scrollen ich nur von oben nach unten. 

Theoretisch könnte man sich doch alle Seiten inkl. Unterseiten nebeneinander vorstellen (in der Navigation sind sie untereinander). Und dann könnte man durch alle Seiten (inkl. Unterseiten) swipen. Von der "letzten" Unterseite zur nächsten "richtigen" Seite. 
Verwirrend erscheint mir das glaube ich nicht. 

Vllt. kann man ja eine Geste einbauen, um von "richtiger" Seite zu "richtiger" Seite (überspringen Unterseite) springen zu können. Beispielsweise mit 2 fingern swipen.

**Comment by peter9teufel** [comment]
Ich werds mir mal anschauen was möglich wäre, da wird sich schon eine gute Lösung finden lassen 👍 

LG,
Peter

**Comment by peter9teufel** [comment]
Hallo,
Version 1.0.28 ist eingereicht, im Google Play Store sollte das Update schon verfügbar sein, bei Apple ist es aktuell noch in Prüfung.

Habs jetzt so eingebaut dass der Swipe die Tabs wechselt wenn Tabs vorhanden sind, wenn man am ersten bzw. letzten Tab weiter swiped wird zur vorherigen/nächsten Seite gewechselt.

LG,
Peter

**Comment by loemic87** [comment]
Hi,

Funktioniert doch Klasse! Vllt bei Gelegenheit noch die Möglichkeit, "unendlich" zu swipen. Also von der letzten Seite auf die erste. Dann wäre ich bei dem Thema wunschlos glücklich.

Vielen Dank für deine Arbeit!

**Comment by peter9teufel** [comment]
Ah, gute Idee, daran hatte ich nicht gedacht. Das lässt sich jetzt noch leicht ergänzen, kommt im nächsten Update 👍

**Comment by peter9teufel** [comment]
Endlosnavigation is seit dem letzten Update möglich.
Lg, Peter
