### ISSUE TITLE
Reihenfolge der Kacheln stimmt nicht 

### ISSUE THREAD

**Issue by Toysman** [peter9teufel/iobmobile-issues#38]
Hallo,

die Reihenfolge der Kacheln stimmt nicht mit der Konfiguration überein, siehe Bilder. Ein Verschieben bringt keine Besserung. 
![IMG_0599](https://github.com/user-attachments/assets/bbbef7d1-8015-45f6-8a1d-d56b70414c87)
![IMG_0598](https://github.com/user-attachments/assets/e76ffeaf-0f82-4d6c-8ab5-da3b25770b49)

**Comment by peter9teufel** [comment]
In der Navleiste neben dem Fragezeichen ist das Sortiericon, mittlerweile wird die Sortierung dort gemacht, die Reihenfolge in den Einstellungen ist nur mehr um in den Einstellungen umzusortieren.
Lg Peter

**Comment by peter9teufel** [comment]
Perfekt 👍 
Was genau meinst du mit "frei positionieren"? Die Reihenfolge kann ja beliebig geändert werden, über die Größe der Kacheln ergibt sich dann die Anordnung je nachdem wie viel Platz jede Kachel benötigt. Gezielt Lücken frei lassen ist mit der Grid Komponente mit der die UI umgesetzt ist nicht möglich soweit mir bekannt ist, also so Szenarien wie ganz oben am Screen 2 Kacheln und ganz unten 2 Kacheln geht nicht.

LG,
Peter

**Comment by Toysman** [comment]
Hallo Peter, 

okay, dann weiß ich erst einmal Bescheid... tolle Arbeit von Dir 👍🏻
