### ISSUE TITLE
Aus dem test Abo ins Pro Abo

### ISSUE THREAD

**Issue by Schwali** [peter9teufel/iobmobile-issues#39]
Hallo zusammen, 

ich habe bei mir die Test Lizenz aktiviert und leider kann ich keine weiteren Datenpunkte mehr anlegen. Aktuell 21. Ich hab mir dann gedacht, naja buchst jetzt die Pro Version, aber auch nach langen suchen auf meinem iPhone und in der Wiki habe keine Möglichkeit gefunden dies zu tun. Die App sagt nur Ich kann es im store verwalten, aber welcher Store? Im AppStore gehts bei mir nicht. Hatte das schon jemand oder bin ich auf den falschen weg?

**Comment by peter9teufel** [comment]
Hi!
Normalerweise wenn ein Limit erreicht ist, kommt ein Popup, dass das Pro Abo nötig ist, über dieses kommt man dann zum Kaufbildschirm. Wenn du aber einen Account angelegt hast und die 30 Tage noch nicht um sind, kannst du mir gern per PN deine E-Mail Adresse und wann du dich registriert hast schicken, dann schau ich ob das Ablaufdatum für die Gratis Testzeit korrekt hinterlegt ist.

LG,
Peter

**Comment by peter9teufel** [comment]
Hi, danke für die E-Mail, hab gerade nachgesehen und das Datum für die 30 Tage gratis Trial ist korrekt mit 25.08.2024 hinterlegt.

Geh mal in die Einstellungen und auf den Tab "Account", was steht dort bei "IOB PRO Abo"? Beziehungsweise wenn du dort auf "Backup prüfen" gehst, kommt in der Backup Übersicht auch ein Tab "Lokal" in dem die Konfigurationen aufgelistet sind inkl. der Anzahl Seiten und Datenpunkte.

Welcher Fehler kommt denn genau? Kannst du eventuell einen Screenshot schicken?

LG,
Peter

**Comment by Schwali** [comment]
Hey,

Ich glaube das hat sich grade von selbst erledigt.😉 
Ich habe jetzt zum testen mal einzelne Datenpunkte gelöscht und dann aus dem Backup das Projekt wieder geladen. Momentan kann ich wieder Datenpunkte hinzufügen. 

Das buchen des PRO ABOs geht weiter hin nicht. Mal schauen wenn die testzeit abläuft was er dann macht. Dies erstmal nur als Info. 

Danke für die Mühe!
