### ISSUE TITLE
Gerät: DasWetter keine Datenpunkte

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#4]
Hallo,

ein wichtiger Adapter DasWetter da kommen keine Daten.

https://github.com/rg-engineering/ioBroker.daswetter

LG
Sigi

**Comment by peter9teufel** [comment]
Hi,
den Adapter hab ich eh auch aktiviert bei mir aber bisher noch nicht getestet, daher ists mir noch nicht aufgefallen. Schau ich mir an.

LG

**Comment by peter9teufel** [comment]
Hi!
Hab ein Update (Version 1.0.2) eingereicht, bei Google Play sollte es in den nächsten Minuten verfügbar sein, im App Store wartet es aktuell auf die Überprüfung und Freigabe von Apple (dauert üblicherweise max. 1 Tag, oft aber auch nur 3-4 Stunden). Die Datenpunkte für Adapter daswetter werden jetzt korrekt geladen und können verwendet werden.

Ich hab mir auch gleich notiert eine eigene Karte für DasWetter zu ergänzen damit die Icons etc. verwendet werden können (evt. eine Karte die direkt Höchst/Tiefsttemperatur, Icon anzeigt).

Wenn das Update auch von Apple freigegeben wurde geb ich nochmal kurz Bescheid hier, gib dann kurz Bescheid ob es mit Version 1.0.2 jetzt klappt.

LG,
Peter

**Comment by peter9teufel** [comment]
wie in #8 sichtbar kommen die Datenpunkte vom DasWetter Adapter jetzt, daher close ich hier mal :+1:

**Comment by sigi2345** [comment]
> wie in #8 sichtbar kommen die Datenpunkte vom DasWetter Adapter jetzt, daher close ich hier mal 👍

Ja geht jetzt, aber in 8 ist es der weatherunderground Adapter.
