### ISSUE TITLE
Sub-Navigation funktioniert nicht mehr

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#40]
Moin Peter,

da bin ich wieder.
Hab mir grad das neue Update gezogen und leider haben sich da ein paar Fehler eingeschlichen.

Bei den Einzelwerten funktioniert nun die Sub-Navigation nicht mehr.

Und wenn man einen Datentyp mit Einzelwert ändern will, kommt diese Fehlermeldung:

![image](https://github.com/user-attachments/assets/4634c1be-33ba-4109-a1d0-743eb00ec6d8)

Ich habe keinen On/Off Datenpunkz definiert.

Viele Grüße

Patrick

**Comment by peter9teufel** [comment]
Ah, doofer Fehler, sorry, beheb ich gleich. Danke für den Hinweis!
LG,
Peter

**Comment by peter9teufel** [comment]
Das mit der Subnavigation kann ich nicht nachstellen, funktioniert bei mir wie bisher, ich fix mal den Fehler mit dem Trigger Datenpunkt, dann kannst du die DP Einstellungen nochmal fehlerfrei anschauen.
LG

**Comment by HackyPaddy** [comment]
Vor dem Update lief die Sub-Navigation perfekt.
Jetzt klickt man auf die Kachel, es folgt eine kleine Animation, aber er wechselt die Seiten nicht mehr.

Wenn der Fix nachher online ist, speichere ich den Datenpunkt nochmal neu ab und versuche es :)

**Comment by peter9teufel** [comment]
Seltsam, konnte ich in meinen Tests nicht reproduzieren. Update ist eingereicht, sobald es von Apple geprüft wurde sollts im Store aufscheinen. Probiers dann nach dem Update nochmal und gib Bescheid.

Danke nochmal für den Hinweis!

LG,
Peter

**Comment by peter9teufel** [comment]
Hi nochmal,
Update wurde eben von Apple freigegeben.

LG,
Peter

**Comment by HackyPaddy** [comment]
Nun kommt die Meldung mit den Tigger nicht mehr, aber die Sub-Navigation geht leider nicht.

Auch wenn ich Datenpunkte neu anlege, gleiches Verhalten.

Es wird die gleiche Seite neu geladen, aber nicht auf die einstellte Seite gesprungen.

**Comment by HackyPaddy** [comment]
Noch kurz nen Nachtrag.
Wenn ich eine Sub-Navigation auf eine andere Hauptseite oder deren Unterseite lege, dann klappt es.

Gehe ich die Sub-Navi auf eine andere Unterseite in der gleichen Hauptseite, dann geht es nicht...

**Comment by peter9teufel** [comment]
Ah, das ist natürlich ein guter Hinweis, Sub-Nav innerhalb der gleichen Hauptseite hab ich glaub ich nicht getestet. Gab da Änderungen für die Swipe-Navigation, da hat sich vermutlich was eingeschlichen.

Aber jetzt weiß ich ja wo ich suchen muss 🙂 Schau ich mir an 👍 

LG

**Comment by HackyPaddy** [comment]
Die Sub-Navigation funktioniert wieder :) 

Deshalb... close :)
