### ISSUE TITLE
Zeitstempel bei allen Widgets

### ISSUE THREAD

**Issue by loemic87** [peter9teufel/iobmobile-issues#41]
Hi,

ich fände es extrem hilfreich, wenn bei allen Widgets die Anzeige des Zeitstempels für die letzte Änderung möglich wäre.
Bei mir betrifft es konkret Boolean Status Widgets.

**Comment by peter9teufel** [comment]
Wird ergänzt, könnte aber noch ein paar Tage dauern, fahre FR Nacht ans Meer und mach mal ne Woche Auszeit mit der Family 🙂 

LG,
Peter

**Comment by loemic87** [comment]
Genieß die Auszeit! Die App ist schon super und deine Reaktionszeit echt kurz! Gönn dir Ruhe!

**Comment by peter9teufel** [comment]
Boolean Status hat den Zeitstempel seit dem letzten Update.

Lg, Peter
