### ISSUE TITLE
Widget mehrere Werte - Einheit des ersten Datenpunkts 

### ISSUE THREAD

**Issue by loemic87** [peter9teufel/iobmobile-issues#42]
Hi,

Ich nutze das Widget "mehrere Werte" um die Daten eines Sensors (Temperatur, rel. Luftfeuchtigkeit und Luftdruck) anzuzeigen. 
Mir fehlt die Möglichkeit, für den ursprünglich ausgewählten Datenpunkt die Einheit zu definieren (°C z.B. wenn ich das Widget mit dem DP für die Temperatur beginne).

**Comment by peter9teufel** [comment]
Seit dem letzten Update kann auch der primäre Datenpunkt vollständig konfiguriert werden.

Lg, Peter
