### ISSUE TITLE
Homematic Jalousien (Lamellen) Ansteuerung

### ISSUE THREAD

**Issue by philg1234** [peter9teufel/iobmobile-issues#43]
Hallo,

ich finde die HM Rollladen Steuerung bereits klasse.
Ist es angedacht, eine Jalousien/Lamellen-Ansteuerung zu implementieren?

Dies ist gerade ein Knackpunkt, weswegen man tatsächlich die APP wechseln muss um die Lamellen Einstellung an den Jalousien einzustellen.

Vielen Dank.

Grüße
Phil

**Comment by peter9teufel** [comment]
Hi!
Hab ich zwar selber nicht, bau ich dir aber gerne ein 🙂 Kannst du mir mal die Datenpunkte schicken mit denen du die Jalousien steuerst? Vermutlich ähnl. wie beim Rollladen ein Level DP 0-100% und ein Stopp DP, aber mit welchen werden die Lamellen gesteuert? Screenshot mit allen DP einer Jalousie aus der Web UI wär vermutlich schon mal OK. Dann schau ichs mir an und implementier einen neuen Datenpunkt Typ dafür in der App.

Wird aber etwas dauern, fahr FR Nacht für eine Woche ans Meer, danach wird wieder entwickelt 🙂 

LG,
Peter

**Comment by philg1234** [comment]
Hey Peter,

vielen Dank für die schnelle Antwort und die Hilfe mit dem Aktor.
Anbei der Screenshot der Datenpunkte. Ich hoffe es ist ausreichend, ansonsten liefere ich natürlich gerne mehr:

![image](https://github.com/user-attachments/assets/239981e0-7f5c-4bac-8e18-d28561ae0482)


Ich bin gerade dabei deine App zu testen und durch diese werde ich vermutlich den Wechsel des führenden Systems zu ioBroker durchführen.

Lange hat mich die APP Thematik davon abgehalten und bisher bin ich von deiner Arbeit begeistert 😊✌️.
Nach den Tests, werde ich dann zur Pro Version wechseln.

Viele Grüße und einen schönen Urlaub.

Phil

**Comment by peter9teufel** [comment]
Das hilft mir schon, ich schau mir das an ob ich es als optionales Feld beim Rollladen Typ dazugebe, evt. ist es verständlicher wenn ich dafür einen eigenen Datenpunkt Typ "Raffstore/Jalousie" ergänze, muss ich mir anschauen.

LG,
Peter

**Comment by peter9teufel** [comment]
Hi nochmal,
ich hätte es jetzt in ersten Variante mal mit einem Slider implementiert, gibt beim generischen Typ "Rollladen" dann die Möglichkeit zusätzlich optional den DP für den Lamellen Level zu konfigurieren. Wenn konfiguriert wird in der Kachel zusätzlich ein Slider angezeigt über den der Level für die Lamellen geändert werden kann.

<img width="192" alt="Bildschirmfoto 2024-08-27 um 21 49 22" src="https://github.com/user-attachments/assets/d16270f2-4cdf-4b8a-be79-55e8c1fe1dd9">

bzw. wenn "Aktuelle Position anzeigen" aktiviert ist -->

<img width="205" alt="Bildschirmfoto 2024-08-27 um 21 48 13" src="https://github.com/user-attachments/assets/65a0d313-9f13-4834-9933-e6e9df060e36">

ich habs jetzt mal beim generischen Typ "Rollladen" ergänzt, da hier ohnehin schon der Stop Datenpunkt separat konfiguriert werden muss und hier somit die Erweiterung leichter möglich ist.

Wäre das eine Variante die passen würde? Wenn der Weg über rauf/runter/stop Buttons wie für den normalen Level sein soll wäre wichtig zu wissen, ob der Stop Datenpunkt auch eine Änderung beim Level der Lamellen stoppt, da es ja nur den einen Stop Datenpunkt gibt.

Hab selber zwar Homematic aber leider keine Raffstores, somit kann ichs nicht direkt testen.

LG,
Peter

**Comment by philg1234** [comment]
Hello,

danke für die schnelle Umsetzung.
Finde die Variante mit dem Slider gut 👌.


> Wäre das eine Variante die passen würde? Wenn der Weg über rauf/runter/stop Buttons wie für den normalen Level sein soll wäre wichtig zu wissen, ob der Stop Datenpunkt auch eine Änderung beim Level der Lamellen stoppt, da es ja nur den einen Stop Datenpunkt gibt.

Was meinst du damit? Das man die Lamellen über Hoch / Runter / Stop einstellen kann?

> Hab selber zwar Homematic aber leider keine Raffstores, somit kann ichs nicht direkt testen.

Kein Thema, kann dir hier gerne alle Daten liefern die du benötigst.


-> was mir gerade noch aufgefallen ist.
Momentan ist jes ja nur möglich "HOCH/RUNTER/STOP" zu fahren. Hast du es geplant auch die Höhe mit eizubauen, dass man direkt z.B. auf 50 Prozent fahren kann?

Grüße
Phil

**Comment by peter9teufel** [comment]
nvm vergiss das mit Hoch/Runter/Stop für die Lamellen, war ein Denkfehler, das mit dem Slider sollte schon mal gut klappen.

bzgl. Wert direkt wählen, da wär jetzt mal der Plan wenn man den aktuellen Stand des Rollladens in der Kachel anzeigen lässt, also so --> 

![Bildschirmfoto 2024-08-28 um 08 04 09](https://github.com/user-attachments/assets/adb41124-a12a-4151-901c-c46988621bdc)

dann kann man auf den Wert tippen und es öffnet sich ein Popup mit Slider um den Wert zu ändern -->

![Simulator Screenshot - iPhone 14 - 2024-08-28 at 08 02 52](https://github.com/user-attachments/assets/a76dc595-b595-4961-afcb-071d59ab3b1c)

ich teste grad noch wo ich in der Kachel dieses Popup triggern könnte wenn der aktuelle Wert nicht eingeblendet ist, also in diesem Zustand -->

![Bildschirmfoto 2024-08-28 um 08 06 14](https://github.com/user-attachments/assets/340b971c-8c7b-4669-a0b9-ec771364662a)

würde diese simple, kleine Kachel nämlich ungern unnötig vergrößern.

LG,
Peter

**Comment by philg1234** [comment]
> nvm vergiss das mit Hoch/Runter/Stop für die Lamellen, war ein Denkfehler, das mit dem Slider sollte schon mal gut klappen.

Alles klar, du brauchst also dafür erstmal nichts mehr von mir?

> bzgl. Wert direkt wählen, da wär jetzt mal der Plan wenn man den aktuellen Stand des Rollladens in der Kachel anzeigen lässt, also so -->

Bildschirmfoto 2024-08-28 um 08 04 09

dann kann man auf den Wert tippen und es öffnet sich ein Popup mit Slider um den Wert zu ändern -->

Finde ich mega 👌

> ich teste grad noch wo ich in der Kachel dieses Popup triggern könnte wenn der aktuelle Wert nicht eingeblendet ist, also in diesem Zustand -->

Bildschirmfoto 2024-08-28 um 08 06 14

würde diese simple, kleine Kachel nämlich ungern unnötig vergrößern.

Verstehe ich. Sehr gute Frage wo dies platziert werden kann.
Eventuell mit einem langen halten auf die Options möglich?

Grüße
Phil

**Comment by peter9teufel** [comment]
grad noch so eingebaut, wenn man die Kachel irgendwo klickt wo nicht direkt einer der Buttons ist kommt das Popup, funktioniert somit auch in der kleinen Variante 👍 

ich werde dann heute noch voraussichtlich ein Update einreichen, die Lamellen Stellung ist dann mit der Slider Variante drinnen, dann kannst du das einfach mal testen ob es so funktioniert 🙂 

LG

**Comment by philg1234** [comment]
Mega. Werde dir dann direkt Rückmeldung geben.

Grüße

**Comment by philg1234** [comment]
Hey Peter,

Update kam nur bei Android an und ich habe es getestet.

FolgendeS Problem/Herausforderung.

Mit dem neuen Slider funktioniert alles problemlos, hoch runter, Stop und die Prozentanzeige.

Nun ist das mit der Lamellenansteuerung etwas eigen.

Und zwar, wenn ich die Lamellenstellung über den Schieber ändere passiert nichts.
Erst wenn ich dann nochmal den Wert zu vor anfahren, dann wird die Lamelle dementsprechend eingestellt.

Bei anderen Apps ist es ähnlich und es gibt deswegen den übernehmen Button um vermutlich nochmal den gleichen Wert der höhe zu senden.

Ich hoffe du verstehst was ich meine, ansonsten werde ich es nochmals genauer beschreiben.

Danke.

Viele Grüße 
Phil

**Comment by peter9teufel** [comment]
Verstehe, sollte kein Problem sein, wenn der Lamellen Wert geändert wird schicke ich einfach die aktuelle Höhe nochmal gleich mit, bau ich ein 👍

**Comment by peter9teufel** [comment]
Update (Version 1.0.30) ist online, ab sofort wird nach Änderung der Lamellenstellung auch der aktuelle Level noch mal gesendet. Teste bitte mal obs jetzt klappt.

LG

**Comment by philg1234** [comment]
Getestet -> Funktioniert.

Danke.
