### ISSUE TITLE
Darstellung auf dem Home Bereich

### ISSUE THREAD

**Issue by philg1234** [peter9teufel/iobmobile-issues#44]
Hi,

eine Frage in Bezug auf die Darstellung auf dem Home Bereich.
Es kann durchaus sein, dass es die Funktion gibt, ich diese aber noch nicht kenne :D.

Momentan ist es ja lediglich möglich sich neue Seiten zu erstellen, welche durch den Klick auf die 3 Striche oben links ausgewählt werden können oder als Unterseite in z.B. in die Home Seite integriert werden können.
Dort gibt es dann die Funktion der Tabs (Unterseite) oder Als Bereich auf der Hauptseite anzuzeigen.

- Was ich eine super Ergänzung fände, wenn man z.B. auf der Home Seite sich **Kacheln** wie z.B. "Licht EG" / "Licht OG" / "Rollladen EG" / "Außenbereich" usw ... definieren könnte, welche dann nach einem Klick in den jeweiligen Tab springen und diese Seiten öffnen würden. Also quasi eine Verlinkung.

Ideal wäre natürlich die Kacheln selbst wie bei den Datenpunkten gestalten zu können " 1x1 oder 1x2 " etc.

- Zusätzlich wenn man z.B. in die Kachel "Licht EG" gesprungen ist, mit einem Swipe nach links wieder auf die Home Seite zurückkehren kann.

Ich finde die Tabs bereits klasse, wenn man allerdings sehr viele Tabs (Unterseiten) hat, muss man doch recht weit scrollen um ans Ziel zu kommen.

Vllt fänden es auch weitere sehr Interessant, wenn es überhaupt umzusetzen ist.

Danke.

Viele Grüße
Phil

**Comment by philg1234** [comment]
Edit:

ich habe soeben beim einbinden der Fensterkontakte bemerkt, dass bei einigen Datenpunkten eine Verlinkung auf eine Subpage möglich ist.

Dies könnte man natürlich dann nutzten um das von mir beschrieben Szenario umzusetzen ✌️ .

Nun stellt sich für mich nur die Frage, was für einen Datenpunkt nutzte ich am besten dafür?
Ich könnte natürlich z.B. einen Fensterkontakt dafür missbrauchen.

Sobald ich z:B. versuche einen Userdata eigens erstellten Datenpunkt zu nutzen, lädt und lädt der Bildschirm nur und das ICON wird nicht angezeigt.
Setzte ich nebenan einen z.B. Fensterkontakt (missbraucht), wird dieser direkt geladen.

**Comment by peter9teufel** [comment]
Subnavigation hat aktuell einen Bug wenn zu einer Unterseite auf der gleichen Hauptseite navigiert werden soll, wird im nächsten Update behoben. Aber eine Fensterkontakt Kachel sollte als „Missbrauch“ funktionieren, der DP könnte ein eigens dafür angelgter im Userdata Ordner sein vom Typ Boolean und Wert „true“.

ich überleg mal ob ich elegant eine Möglichkeit einbauen kann damit man Icon Kacheln ohne DP dahinter anlegen kann die rein zur Subnavigation verwendet werden können.

LG, Peter

**Comment by philg1234** [comment]
Vielen Dank für die Info.

Den Bug habe ich soeben auch bemerkt und freue mich auf das Update.
Ich habe jetzt mehrere Datenpunkte vom typ Boolean angelegt und in der App als Typ Fensterkontakt deklariert.

So kann nun super gesprungen und auch ein Symbol verlinkt werden.
Dies kann super als Workaround durchgeführt werden, bis du eine eventuell elegantere Lösung gefunden hast.

###
Was mich an der App mit am meisten begeistert ist, die fast quasi Live Aktualisierung 😍.

**Comment by peter9teufel** [comment]
Hi nochmal,
zurück aus dem Urlaub und hab grad nochmal über das Thema nachgedacht und ich denke ich hab einen Weg gefunden über den ohne extra Datenpunkt im Hintergrund Kacheln zur Subnavigation hinzugefügt werden können. Ich werd mir das fürs kommende Update mal anschauen.

LG,
Peter

**Comment by philg1234** [comment]
Hi Peter,

ich wollte mich kurz hierzu nochmals bei dir melden.

Wie du ja weißt, hatte ich den Workaround mit dem Fensterkontakt für den Wechsel auf den Home Bereich konfiguriert.
Dies funktioniert soweit sehr gut, allerdings gibt es etwas Probleme, wenn Unterseiten als Tabs konfiguriert sind.
Hierbei müsste man zusätzlich auf jede Unterseite einen DP einsetzten um von dort aus wieder auf z.B. den Home Bereich zurück zu kommen.

Alternativ könnte man natürlich in eine Richtung swipen oder über das Navigations Menü die Seite aufrufen.

Mir ist gestern hierzu eine Idee gekommen, ich weiß nicht ob es umsetzbar ist.
Es gibt doch auf jeder Seite mittig oben die Überschrift der Seite (Neben den 3 Strichen links und der 123 mit den Strichen Rechts).
Wäre es möglich, dass man diese klickbar macht und dort ein Navigation hinterleg könnte?
Als Beispiel befindet man sich in der Seite Licht und hat oben LIcht stehen -> wenn man nun auf die Schrift Licht klickt würde es einen zurück auf die hinterlegte Seite navigieren (z.B. Home Bereich).
So könnte man sich die DP sparen und hätte auch die Lösung, wenn es Unterseiten als Reiter gibt.

Ich hoffe es ist irgendwie verständlich was ich meine 😅.

Anbei noch ein Video. Bei mir wäre z.B. das Problem beim Reiter "Licht".


https://github.com/user-attachments/assets/1261c636-f42a-49ff-beaa-6bc7023a8b63

Vielen Dank.

Grüße
Phil

**Comment by peter9teufel** [comment]
Hi,
ich arbeite grad an einem größeren Update, sollte diese Woche hoffentlich fertig werden, in dem ist es dann möglich in den Seiten Einstellungen (Sortier-Icon in der Navigationsleiste, in deinem Screenshot rechts neben "Alarm" Titel") nicht nur die Sortierung anzupassen, sondern auch Elemente zur Unterteilung einzubauen (sieht dann ähnlich wie Unterseiten die als Bereich angezeigt werden aus) und auch um eigene Kacheln hinzuzufügen die nur zur Navigation genutzt werden ohne dass das dafür extra ein Datenpunkt ausgewählt werden muss.

Ich denke mal, damit solltest du es dann eigentlich gut umsetzen können, da die zusätzlichen DP wie im Workaround dann nicht mehr nötig sind.

Ich würd dich bitten noch auf das Update zu warten, evt. passts damit dann, wenn dann noch immer was erweitert werden muss kann man auf dem dann aufbauen.

LG,
Peter

**Comment by philg1234** [comment]
Moin Peter,

Update ist eingespielt und die meisten Seiten bereits umkonfiguriert.
Gliederung + Trennlinie funktionieren top ✌️

Macht das ganze jetzt wesentlich einfacher, die Datenpunkte auf der richtigen Seite zu platzieren.

Klasse Umsetzung 💪💪🤲.

Vllt ergänzend für das nächste Update noch eine Idee.
Du siehst in meinem Screenshot, dass ich die Variante zurück Zum Home Bildschirm über die ganze Breite gezogen hatte:

![image](https://github.com/user-attachments/assets/53a59fc0-4931-4a8e-93b6-75f575558b93)

Momentan ist es nicht möglich die Größe einzustellen. Eventuell kannst du dies noch nachziehen, dass man die Größe über die komplette breite gestalten könnte.

Viele Grüße
Phil

**Comment by peter9teufel** [comment]
Danke für den Hinweis, work in progress, kommt im nächsten Update 👍 

![Simulator Screenshot - iPhone 14 - 2024-10-09 at 16 36 35](https://github.com/user-attachments/assets/57990d19-9781-482a-860e-00e729993acc)

**Comment by peter9teufel** [comment]
Update sollte seit gestern verfügbar sein, ich mach dann hier mal zu 😁

Lg, Peter
