### ISSUE TITLE
HTML Weiterleitung - Browser

### ISSUE THREAD

**Issue by philg1234** [peter9teufel/iobmobile-issues#45]
Hallo,

momentan ist es ja bereits möglich HTML Seiten in der APP einzubinden, was auch super funktioniert (Scrollen ist natürlich etwas schwer, wenn die HTML Seite nicht komplett angezeigt wird).

Idee:

Es wäre klasse, wenn man die Möglichkeit hätte von einem Datenpunkt eine URL im Browser extern öffnen zu können.
Dies durch klick auf den integrierten Datenpunkt mit oder ohne Abfrage.

Beispiel:

Ich nutzte EVCC als PV Überschuss Laden und habe diverse Werte über einen Datenpunkt in der APP (Mehrere Werte) integriert.
Somit sehe ich sehr schön ob und welches Auto angeschlossen ist, ob geladen wird etc ...

Angenommen ich möchte jetzt doch Einstellungen ändern, gefällt mir die EVCC Oberfläche eigentlich ganz gut und würde gerne direkt dort hin springen.
Dies wäre doch klasse, wenn man dies in einem Datenpunkt hinterlegen könnte. Ähnlich wie die Navigation zu einer anderen Seite nur in diesem Fall zu einer externen URL im Browser.

Viele Grüße
Phil

**Comment by peter9teufel** [comment]
Gute Idee, werde ich ergänzen.

LG,
Peter

**Comment by peter9teufel** [comment]
Seit dem letzten Update kann bei der Sub-Navigation die bisher nur auf andere Seiten führen konnte alternativ ein DP ausgewählt werden in dem eine externe URL liegt die dann im Browser geöffnet werden kann.

LG,
Peter
