### ISSUE TITLE
HomeMatic Heizungs-Ansteuerung (Datenpunkt) - Wandthermostat

### ISSUE THREAD

**Issue by philg1234** [peter9teufel/iobmobile-issues#46]
Hey Peter,

ähnlich wie beim Jalousien Aktor wäre es klasse, wenn man für die Heizungs-Einstellung einen eigenen Datenpunkt hätte.

Hier der Auszug des Datenpunkts eines Homematic IP Wired Wandthermostats:

![image](https://github.com/user-attachments/assets/568cb9ff-2567-4515-9307-e875fe02006f)

Auch hier z.B. noch eine Idee, wie es andere in der App eingebaut haben (Design):

Darstellung in der App Übersicht:

![image](https://github.com/user-attachments/assets/83c2c5a7-f4d4-4798-b4e8-c8cccd8b2abe)

Und in der Bedienung:

![image](https://github.com/user-attachments/assets/349e0d6c-edf8-413c-aa46-bf5ee5c2a6aa)

Vielen Dank.

Grüße
Phil

**Comment by peter9teufel** [comment]
Hi,
schau ich mir an, wird aber etwas aufwändiger sein. Temperatur ändern ist klar, aber was ist da genau der Workflow wenn du Modus, Boost oder Profil änderst? Damit ich die Verwendung noch etwas genauer verstehe.

LG,
Peter

**Comment by philg1234** [comment]
Danke dir 👌
Ich sag mal so, Temperatur mit einem schönen Regler + die Luftfeuchtigkeit ist schonmal ein sehr guter Start und das wichtigste.


Was genau meinst du mit Workflow?
- Boost
  > wird die Heizung für ich meinte 30 Sekunden auf Vollgaas geschaltet und danach wieder auf den alten Wert zurück
- Modus
 > Hier kann zwischen Auto und Manuell und ECO gewählt werden
    Dementsprechend zieht ein Zeitplan oder eben die manuellen EInstellungen
- Profil
 > Hier kann das Wochenprofil ausgewählt werden, welches in dem Aktor konfiguriert werden kann

**Comment by peter9teufel** [comment]
Update ist eingereicht und sollte heute, spätestens morgen verfügbar sein (Version 1.0.32).

Modus, Boost, Profil und Zieltemperatur kann gesteuert werden indem auf das jeweilige Element in der Kachel geklickt wird, aktuelle Temperatur und Luftfeuchtigkeit werden angezeigt.

![Bildschirmfoto 2024-09-26 um 12 58 33](https://github.com/user-attachments/assets/0268fe90-d5cc-483c-9391-4b3234bfc4d1)

Zum Konfigurieren einen beliebigen DP auswählen (zB. ACTIVE_PROFILE).

Teste es mal wenn das Update verfügbar ist, ich hab wie gesagt selbst kein so Thermostat, deshalb ist das alles etwas theoretisch hier bei mir im Test 😄 

LG,
Peter

**Comment by philg1234** [comment]
Mega.

Werde es direkt testen, sobald das Update eingespielt ist.
Gebe Rückmeldung.

**Comment by philg1234** [comment]
Guten Morgen,

ein kurzes Update zum HM Thermostat.
Vielen Dank für die Umsetztung.

Die Einstellung der Temperatur funktioniert perfekt 👌.
Hier eventuell noch eine Idee.

Es ist ziemlich schwer, die genaue Temperatur mit dem Schieberegler zu treffen.
Eventuell wäre es irgendwann möglich noch ein + / - neben dem Regler einzubauen um die Temperatur fein einzustellen?

Einen Fehler gibt es noch beim ändern des Modus.
Sobald der Modus von "Manuell" auf "Auto" geändert wird, erscheinen kurz die Profile zur Auswahl -> die Temperatur wird auf  4,5 also Off gestellt und der Modus stellt sich automatisch wieder auf "Manuell".



Uploading screen-20240928-094311.mp4…



Viele Grüße
Phil

**Comment by peter9teufel** [comment]
Hi! Hab eine Vermutung, es gibt da zwei DP, CONTROL_MODE und SET_POINT_MODE, glaub da hab ich was verdreht, schau ich mir an.

LG

**Comment by peter9teufel** [comment]
Update ist eingereicht, das Wechseln zwischen Manuell/Auto sollte mit dem Update (Version 1.0.33) jetzt passen. Hab außerdem gleich die +/- Buttons im Temperatur Slider Popup dazu gebaut, mit diesen kann man die Temperatur in 0.5° Schritten anpassen.

Und wie immer --> je nachdem wie lange Apple und Google mit der Prüfung rumtun sollte das Update heute oder spätestens morgen verfügbar sein 😄 

LG

**Comment by philg1234** [comment]
Hello,

habe das ganze nochmal getestet und funktioniert perfekt 👌👌.
Vielen Dank für die super schnelle Umsetzung.

Viele Grüße
Phil

**Comment by Rudi-Ment** [comment]
Super App.
Das Heizungssteuerungs-Widget finde ich auch gut, aber diese funktionieren mit den NICHT-IP-Geräten nicht.
Kann man da noch was machen ?

Die Datenpunkte sehen so aus:

![Image](https://github.com/user-attachments/assets/a8d1d41f-4e24-42b5-a2de-6e2f2463556b)
