### ISSUE TITLE
Account sharing

### ISSUE THREAD

**Issue by ChefkochTS** [peter9teufel/iobmobile-issues#47]
Hallo Zusammen, wie funktioniert das Account sharing genau?
Muss ich die komplette konfiguration mit Mqtt usw. machen und dann ein backup hoch laden?

Gruß
Thorsten

**Comment by peter9teufel** [comment]
Hi!
Genau, du machst einen Account auf deinem Hauptgerät das du regelmäßig nutzt (zB. Smartphone), auf dem sollte auch wenn nötig das Abo gemacht werden. In den Einstellungen im Tab "Account" kannst du dann ein Backup machen, wenn man an einer Konfiguration was ändert wird zudem immer gefragt ob ein Backup im Account gemacht werden soll.

Auf deinem anderen Gerät meldest du dich dann mit deinem Account an und gehst in den Einstellungen im Account Bereich auf "Backup wiederherstellen". 

Ein eventuell vorhandenes Pro Abo kann auch geteilt werden. Wenn das andere Gerät die gleiche Plattform (Android oder iOS) ist, ist das Abo über den Account (Google Account bzw. Apple ID oder Apple Family Sharing) ohnehin verfügbar. Wenn das andere Gerät auf der anderen Plattform ist, wird die Abo Gültigkeit über den Account geteilt, so kann das Pro Abo auf bis zu 5 Geräten der anderen Plattform genutzt werden. Immer wenn die App gestartet wird, wird die Gültigkeit des Abos im Account aktualisiert. Wenn du also zB. auf deinem iPhone, das du regelmäßig nutzt, das Pro Abo nimmst, zu Steuerung aber günstigere Android Tablets verbaut hast, dann kannst du das Pro Abo mit diesen Android Tablets (max. 5 Stk.) teilen.

LG,
Peter

**Comment by ChefkochTS** [comment]
Danke für die Hilfe.
Wenn ich mich mit meinem Account auf dem Handy meiner Frau Anmelde sagt er das es kein Aktives Pro Abo gibt?
Müsste er das nicht sofort erkennen?

**Comment by peter9teufel** [comment]
Welche Plattform? Innerhalb der gleichen Plattform (zB. iOS) erfolgt das Sharing der Lizenz über zB Family Sharing bei Apple (bei Google gibts sowas auch soweit ich weiß). Nur Von iOS zu Android oder umgekehrt kann über den IOB Account das Abo geteilt werden, da es da ja keine Möglichkeit von Haus aus gäbe.
Lg

**Comment by loemic87** [comment]
@peter9teufel das gleiche "Problem" habe ich hier auch. 

2 Android Geräte, 1x ich (eigener Google-Account, Accountinhaber für iob mobile und auch Abo-Nutzer) und 1x meine Frau (auch eigener Google-Account, eingeloggt bei iob-mobile mit meinem Account). 

Wir sind als "Familie" beim Playstore verknüpft und nutzen auch die Familienmediathek vom Playstore. Das iob-mobile-Abo kann hier jedoch nicht geteilt werden, so wie es aussieht. Bei meiner Frau (angemeldet mit meinem Login in iob mobile) steht auch "kein aktives Pro Abonnement).

**Comment by peter9teufel** [comment]
Hi,
hab grad nochmal nachgelesen, Google Play Family Library teilt nur Apps innerhalb der Familie, unterstützt aber keine Abos. Verhält sich in diesem Punkt also anders.

Ich schaus mir an, es gibt ja bereits die Möglichkeit für 5 Geräte der anderen Plattform das Abo über den Account zu teilen. Das könnte ich öffnen damit es auch Geräte der selben Plattform sein können.

LG,
Peter

**Comment by peter9teufel** [comment]
Update wird heute noch eingereicht werden, sollte dann also heute oder morgen spätestens online sein im Normalfall. Habs jetzt geändert, dass das Abo Sharing über den IOB Account auch auf der selben Plattform erlaubt ist, also nicht nur Cross Platform, das Limit von 5 Devices bleibt dabei unverändert.

LG

**Comment by peter9teufel** [comment]
Update (Version 1.0.30) ist seit gestern online, testet bitte mal ob das Abo jetzt auch von Android --> Android geteilt werden kann über den IOB Account.

LG, Peter

**Comment by loemic87** [comment]
Hi @peter9teufel,

Funktioniert hier einwandfrei. Vielen Dank :-)
