### ISSUE TITLE
Alexa Echo Steuerung

### ISSUE THREAD

**Issue by loemic87** [peter9teufel/iobmobile-issues#48]
Hi,

besteht die Möglichkeit, ein Widget für die Player-Steuerung von Alexa/Echo-Geräten einzubauen? Also wo dann aktueller Titel, Laufzeit, Restlaufzeit und Buttons für die Steuerung (Play, Pause etc.) eingebaut sind?

**Comment by peter9teufel** [comment]
Sollte möglich sein, gute Idee, kann ich selbst auch brauchen eigentlich 😅 ich überleg mir mal was 👍

**Comment by sigi2345** [comment]
Eventuell eine Multimedia Kachel um auch andere Geräte zu steuern? Verstärker, Sonos usw...

**Comment by peter9teufel** [comment]
Ich glaub ich würde im ersten Schritt mal fertige DP Typen für Sonos und Alexa machen, ist dann einfacher in der Nutzung, da es doch eine ganze Reihe Datenpunkte sind die manuell konfiguriert werden müssten (Cover Image, aktueller Track, aktueller Fortschrit, play/pause/prev/next, Shuffle, Volume). Das sollte dann zumindest mal für die zwei gängisten (und das sind vermutlich im ersten Schritt mal Alexa und Sonos) auch mit wenigen Klicks konfigurierbar sein.

**Comment by peter9teufel** [comment]
Update mit den neuen Typen "Mediensteuerung Alexa" und "Mediensteuerung Sonos" wird heute noch eingereicht, sollte dann also im Normalfall spätestens morgen in den Stores sein.

LG
