### ISSUE TITLE
Seiten swipen und HTML Einbettungen

### ISSUE THREAD

**Issue by HackyPaddy** [peter9teufel/iobmobile-issues#49]
Moin Peter,

mal einen weiteren Fehler für dich.

Ich habe angefangen und E-Chart Diagramme in die App zu integrieren.

Klappt super, aber wenn ich im HTML vergrößern und wischen will, dann interpretiert die App das so, als wenn ich eine Seite wechseln will.

In den Charts kann ich somit nicht vor und zurück gehen, ohne das gleich die nächste Seite in der App kommt. Das natürlich ein bisschen blöd..

Viele Grüße

Patrick

**Comment by peter9teufel** [comment]
Hi,
ich schau mal was mir da schlaues einfällt, evt. eine Möglichkeit ein HTML/Fullscreen HTML in einem neuen Fenster zu öffnen in dem man dann alles machen kann.

Problem ist halt, dass der Swipe als Swipe fürs Navigieren genutzt wird, das jetzt für einzelne DP Typen deaktivieren ist dann auch wieder blöd.

Ich geh mal in mich 😄 

LG

**Comment by peter9teufel** [comment]
Hi,
habs jetzt mal so gemacht, dass man bei HTML Kacheln auf den Titel klicken kann um den Content in einem Popup zu öffnen, da sollte die Bedienung dann klappen, so kommt es sich nicht mit der Swipe Navigation in die Quere. Bei Fullscreen HTML ist rechts unten ein Floating Action Button um das Popup zu öffnen.

LG,
Peter

**Comment by HackyPaddy** [comment]
Moin Peter,

hab das Update gerade geladen.
Perfekt! Mehr gibt's nicht zu sagen :)
