### ISSUE TITLE
Geraet:  Alias keine Datenpunkte

### ISSUE THREAD

**Issue by Ilovegym66** [peter9teufel/iobmobile-issues#5]
Bei mir erscheinen bei Adapter Alias keine Datenpunkte
Meine Struktur in iobroker:
![image](https://github.com/peter9teufel/iobmobile-issues/assets/36229898/891bef5b-bc02-4fba-858a-6abfaebc1937)

**Comment by peter9teufel** [comment]
Alias Adapter hab ich eh auch in Verwendung, schau ich mir an, danke für den Hinweis.

**Comment by peter9teufel** [comment]
Hi!
Hab ein Update (Version 1.0.2) eingereicht, bei Google Play sollte es in den nächsten Minuten verfügbar sein, im App Store wartet es aktuell auf die Überprüfung und Freigabe von Apple (dauert üblicherweise max. 1 Tag, oft aber auch nur 3-4 Stunden). Die Datenpunkte für den Alias Adapter werden bei mir mit dem Update jetzt korrekt geladen und können verwendet werden.

Wenn das Update auch von Apple freigegeben wurde geb ich nochmal kurz Bescheid hier, gib dann kurz Bescheid ob es mit Version 1.0.2 jetzt klappt.

LG,
Peter

**Comment by santa81** [comment]
alias wird jetzt angezeigt. 
Wenn man  den alias Manager verwendet, dann ist darin trotzdem natürlich nichts zu finden.
Dadurch ist die Auflistung von Adapter unter Umständen etwas verwirrend.

**Comment by peter9teufel** [comment]
korrekt, vielen Dank für die Rückmeldung, dass die Datenpunkte jetzt da sind.

LG
