### ISSUE TITLE
Remote Zugriff - wie?

### ISSUE THREAD

**Issue by andiweli** [peter9teufel/iobmobile-issues#50]
Leider fand ich dazu keine Hilfe, aber wie kann ich remote auf meinen ioBroker zugreifen?

**Comment by philg1234** [comment]
Ich denke mal du willst von extern über die App zugreifen können?
Dies ist natürlich eine generelle Grundsatzfrage, wie du dein IoBroker / Netzwerk verfügbar machen willst.

Es gibt natürlich mehrere Methoden von:

- Einfache Portweiterleitung über die Public IP (nicht empfohlen)
- VPN
- Reverse Proxy

**Comment by andiweli** [comment]
Wenn VPN geht, welchen kostenlosen Service würdest du empfehlen? Hab keine Ahnung davon. Aber mein iPhone hat hier unter VPN stehen: IKEv2, IPSEC und ein L2TP Protokoll. 

Kann man damit deine App mit einem ioBroker eines Raspberrys von außerhalb des eigenen WLANs nutzen?

Die ioBroker-eigene App scheitert leider seit knapp über einem Jahr daran und scheinbar ist die Userbase zu klein das zu fixen 🤷🏻‍♂️😂

**Comment by philg1234** [comment]
Ich denke das einfachste wäre für dich, wenn du dich einmal mit VPN befasst.
Ich denke nicht, dass du eine Art Firewall oder ähnliches zuhause hast und deswegen den Router als VPN GW hernehmen solltest.

In diesem Fall z.B. einfach einen IPSEC oder Wireguard Connection auf der Fritzbox konfigurieren.
Hierzu benötigst du natürlich noch ein DynDNS Dienst, welcher deine Public IP Adresse regelmäßig updatet. Ich denke du hast keine static Public IP zur Verfügun.

> Kann man damit deine App mit einem ioBroker eines Raspberrys von außerhalb des eigenen WLANs nutzen?

Was schwebt dir hier vor?
Wenn du ein VPN Tunnel aufgebaut hast, befindest du dich quasi im privaten Netzwerk und kannst alles wie in den eigenen 4 Wänden nutzten.

**Comment by andiweli** [comment]
Fritzbox habe ich hier leider nicht. Glasfaser und ein ZTE Modem. Dahinter ein TPLink X20 Mesh. 

Bin leider derzeit im Ausland, Zugriff auf Modem nicht möglich. Lediglich Mesh via App. 

VPN suche ich eine einfache "headless" Installation. Hab nicht mehr wirklich Lust mich mit sowas noch zu beschäftigen. Deshalb die Frage, ob diese App hier das nicht quasi built-in unterstützt. Hab zuwenig Ahnung wie das programmiert wird. 

Die offizielle App von ioBroker sollte es ja auch unterstützen mit dem kostenpflichtigen Pro Abo das ich habe. Aber die bekommen das seit nem Jahr nicht auf die Reihe.

Danke dennoch für die Antworten.

**Comment by philg1234** [comment]
Ok.

> VPN suche ich eine einfache "headless" Installation. Hab nicht mehr wirklich Lust mich mit sowas noch zu beschäftigen. 

Dann wird es natürlich schwer.

> Deshalb die Frage, ob diese App hier das nicht quasi built-in unterstützt. Hab zuwenig Ahnung wie das programmiert wird.

Wird nicht unterstützt.

>Die offizielle App von ioBroker sollte es ja auch unterstützen mit dem kostenpflichtigen Pro Abo das ich habe. Aber die bekommen das seit nem Jahr nicht auf die Reihe.

Das ist natürlich dumm.

> Danke dennoch für die Antworten.

gerne.

**Comment by peter9teufel** [comment]
Tailscale kannst du dir eventuell anschauen, ist vom Setup überschaubar und für iOS/Android gibts eine App. Hab das mal für einen anderen UseCase getestet und ging einfach und unkompliziert. In Kombination mit ioBroker hab ichs aber noch nicht getestet, das war längere Zeit bevor ich mit der App begonnen habe. Hab mir damals meine Homematic CCU als Exit Node angelegt und kann die WebUI über die interne IP im Browser problemlos erreichen wenn ich mein iPhone über die Tailscale App verbinde.

LG

**Comment by andiweli** [comment]
Mit Tailscale bin ich gestern erfolgreich weiter gekommen. Sehr einfache Einrichtung.
