### ISSUE TITLE
Ersteinrichtung - Port MQTT fix auf 1883

### ISSUE THREAD

**Issue by kueppert** [peter9teufel/iobmobile-issues#52]
Als ich eben das erste mal meine iob-Instanz zu der App hinzugefügt habe, bestand nicht die Möglichkeit, bei MQTT den Port zu ändern. Das konnte ich nur machen, nachdem der Account angelegt war in der mobilen App und dann via editieren des Accounts den MQTT-Port ändern von 1883 auf den von mir genutzten.

**Comment by peter9teufel** [comment]
Das ist in der Tat seltsam 😄 schau ich mir an, danke für den Hinweis.

LG,
Peter

**Comment by peter9teufel** [comment]
Hi,
wurde im letzten Update bereits behoben, ganz vergessen hier zu schließen. Danke nochmal für den Hinweis.

LG,
Peter
