### ISSUE TITLE
Fehler beim Account Login 

### ISSUE THREAD

**Issue by philg1234** [peter9teufel/iobmobile-issues#54]
Hi Peter,

scheint wohl ein Fehler zu geben beim Versuch ins Pro Abo einzuloggen.

Nach der Anmeldung kommt folgende Fehlermeldung 

![1000156785](https://github.com/user-attachments/assets/d37c1143-b74d-4582-929a-5d524999caf7)

Grüße 
Phil

**Comment by peter9teufel** [comment]
Der Hoster bei dem die Accountverwaltung liegt hat einen Ausfall, sollte bald behoben sein laut deren Status Page.

Lg

**Comment by peter9teufel** [comment]
Info vom Hoster dass es wieder funktioniert, gerade bei mir getestet und läuft wieder.

Lg
