### ISSUE TITLE
Full Screen HTML Bug

### ISSUE THREAD

**Issue by Schwali** [peter9teufel/iobmobile-issues#56]
Hallo Peter,
seid dem letzten update geht bei mir das anzeigen von Flow Charts in Full Screen HTML Kachel nicht mehr. Wenn ich auf auf Html Kachel umstelle geht alles. Anderen Link habe ich auch schon probiert. Kann das sein das sich da ein Bug eingeschlichen hat? 

Schöne Grüße

**Comment by peter9teufel** [comment]
Schau ich mir an, welche Charts bindest du da genau ein? E-Charts oder Flot?

LG,
Peter

**Comment by Schwali** [comment]
Flot Charts, es hat vorher super funktioniert.

**Comment by peter9teufel** [comment]
Fehler gefunden, ist im nächsten Update behoben, danke für den Hinweis!

LG,
Peter

**Comment by peter9teufel** [comment]
Hi! Update ist online, sollte wieder passen.

LG, Peter
