### ISSUE TITLE
PopUp und Slider kombinieren

### ISSUE THREAD

**Issue by philg1234** [peter9teufel/iobmobile-issues#58]
Hallo,

folgende Idee:

Momentan ist es so, dass wenn man einen Slider auswählt, man lediglich über den Slider den Aktor ansteuern kann (z.B. Dimmer).
Es wäre klasse, wenn die zwei Typen " Slider und Popup Slider" kombiniert werden können.

So dass man entweder über den Slider die Einstellung durchführt oder wenn man auf das Feld klickt den PopUp Slider zur Verfügung hat.
Oftmals gerade bei Licht (Dimmer) finde ich es etwas schwierig den richtigen Wert nur über den Typ "Slider" zu treffen.

Alternativ oder zusätzlich wäre es auch super, wenn man beim Typ "Popup Slider" anstelle der Zahl den Slider mit dem aktuellen Wert angezeigt bekommt (wie z.B. beim Rollladen).

Vielen Dank.

Grüße
Phil

**Comment by peter9teufel** [comment]
Version 1.0.39 ist online, ich mach hier somit zu.

LG,
Peter
