### ISSUE TITLE
keine Datenpunkte linkeddevice Adapter 

### ISSUE THREAD

**Issue by santa81** [peter9teufel/iobmobile-issues#6]
Eventuell habe ich auch einfach zu viele Datenpunkte in dem Adapter. Der Ladekreis dreht sich dauerhaft. Habe nach 2 Minuten aufgegeben. 
Hätte ich eventuell noch länger warten sollen?

**Comment by peter9teufel** [comment]
Hi! Gibt auch bei einem anderen Adapter ein Problem dass die Datenpunkte nicht geladen werden, eventuell ist die Ursache hier ähnlich. Konnte mir das schon anschauen, wenn ich morgen dazukomme mach ich gleich ein Update. Ich geb dir Bescheid.

Lg

**Comment by peter9teufel** [comment]
Hi!
Hab ein Update (Version 1.0.2) eingereicht, bei Google Play sollte es in den nächsten Minuten verfügbar sein, im App Store wartet es aktuell auf die Überprüfung und Freigabe von Apple (dauert üblicherweise max. 1 Tag, oft aber auch nur 3-4 Stunden). Hab mir zum Test gerade den LinkedDevices Adapter installiert und schnell ein Device erstellt und die Datenpunkte für den LinkedDevices Adapter werden bei mir mit dem Update jetzt korrekt geladen und können verwendet werden.

Wenn das Update auch von Apple freigegeben wurde geb ich nochmal kurz Bescheid hier, gib dann kurz Bescheid ob es mit Version 1.0.2 jetzt klappt.

LG,
Peter

**Comment by santa81** [comment]
@peter9teufel Objekte werden jetzt alle angezeigt.

**Comment by peter9teufel** [comment]
super, danke für die Rückmeldung.
