### ISSUE TITLE
Es werden gar keine Daten dargestellt

### ISSUE THREAD

**Issue by a-i-ks** [peter9teufel/iobmobile-issues#7]
In den Einstellungstab "Datenpunkte" steht lediglich "Füge im Tab Adaoter neue Datenpunkte hinzu".

Im Tab "Adapter" steht dann "Keine Adapter gefunden."

Konfiguration:
Kein HTTPS, Keine Authentifizierung, Kein MQTT

**Comment by peter9teufel** [comment]
Hi! Könntest du mir eine Liste der Adapter schicken die du verwendest? Dann kann ich versuchen das Problem nachzustellen um den Fehler zu lösen. Außerdem wäre noch interessant ob das System auf dem aktuellen Stand ist.

Lg,
Peter

**Comment by peter9teufel** [comment]
kannst du mal im Browser http://:/objects?type=adapter&prettyPrint aufrufen und mir die Ausgabe hier schicken?
also zb. http://192.168.1.100:8087/objects?type=adapter&prettyPrint

der Port muss jener sein, der im SimpleAPI Adapter konfiguriert ist.

LG

**Comment by a-i-ks** [comment]
Ah, ich glaube ich habe den Fehler bei mir schon gefunden. Ich hatte den SimpleAPI Adapter gar nicht installiert, sondern die im WEB-Server enthaltene Simple-API verwendet. Diese scheint aber nur einen abgespeckten Funktionsumfang zu haben und für deine App nicht geeignet zu sein. Mit Installation des richtigen Adapter geht es.

**Comment by peter9teufel** [comment]
Ah super, danke für die Rückmeldung, gut zu wissen.

Lg
