### ISSUE TITLE
Feature-Request: Schriftgröße

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#8]
Hallo,

kann man die Schrittgröße in den Kacheln änderbar machen?

![Screenshot_20240607_083830](https://github.com/peter9teufel/iobmobile-issues/assets/41079106/34d457f1-3da9-4bd7-96fe-02219cbcc429)

LG
Sigi

**Comment by peter9teufel** [comment]
Exakt das gleiche ist mir beim Testen vom DasWetter Adapter auch aufgefallen, werd ich ergänzen.

**Comment by peter9teufel** [comment]
Version 1.0.4 ist bereits eingereicht, ab sofort gibt es für Datenpunkte in der App den Typ "Text", dieser ist exakt für diesen Anwendungsfall gedacht, der Text wird dann automatisch runterskaliert bis zu einer minimalen Font Size von 8. Update für Android im Laufe des Vormittages, für iOS dann vermutlich auch heute im Laufe des Tages (je nachdem wie schnell Apple ist).
