### ISSUE TITLE
Feature-Request: Zeitstempel

### ISSUE THREAD

**Issue by sigi2345** [peter9teufel/iobmobile-issues#9]
Hallo,

kann man bei den Kacheln den Zeitstempel ausblendbar machen?

LG
Sigi

**Comment by peter9teufel** [comment]
aktuell nicht, ergänz ich als Option bei den Datenpunkt Einstellungen, gute Idee

**Comment by AntiHeld889** [comment]
Hallo Peter, es wäre auch schön wenn man den Zeitstempel bei "Eigenen Wert schreiben" ausblenden könnte.

Wirkt dann etwas aufgeräumter und nicht so überladen :)

**Comment by peter9teufel** [comment]
Ah, stimmt, übersehen, ergänz ich.
Lg

**Comment by AntiHeld889** [comment]
Und beim Fensterkontakt die Option bitte hinzufügen dort fehlt sie aktuell :)

**Comment by peter9teufel** [comment]
Wurde angepasst, Version 1.0.15 ist eingereicht und sollte im Laufe des Tages im AppStore und im Google Play Store verfügbar sein.

LG,
Peter
